const iconPaths={grid:'<rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/>',apps:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><path d="M17.5 14v7M14 17.5h7"/>',home:'<path d="m3 11 9-8 9 8"/><path d="M5 10v11h14V10M9 21v-7h6v7"/>',calendar:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M16 3v4M8 3v4M3 10h18"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .34 1.88l.06.06-2.83 2.83-.06-.06A1.7 1.7 0 0 0 15 19.4a1.7 1.7 0 0 0-1 .6 1.7 1.7 0 0 0-.4 1.1V21h-4v-.09A1.7 1.7 0 0 0 8.6 19.4a1.7 1.7 0 0 0-1.88.34l-.06.06-2.83-2.83.06-.06A1.7 1.7 0 0 0 4.6 15a1.7 1.7 0 0 0-.6-1 1.7 1.7 0 0 0-1.1-.4H3v-4h.09A1.7 1.7 0 0 0 4.6 8.6a1.7 1.7 0 0 0-.34-1.88l-.06-.06 2.83-2.83.06.06A1.7 1.7 0 0 0 9 4.6a1.7 1.7 0 0 0 1-.6 1.7 1.7 0 0 0 .4-1.1V3h4v.09A1.7 1.7 0 0 0 15.4 4.6a1.7 1.7 0 0 0 1.88-.34l.06-.06 2.83 2.83-.06.06A1.7 1.7 0 0 0 19.4 9c.15.38.37.72.66 1 .3.28.7.42 1.1.4H21v4h-.09A1.7 1.7 0 0 0 19.4 15Z"/>',search:'<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>',bell:'<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M14 21h-4"/>',menu:'<path d="M4 6h16M4 12h16M4 18h16"/>',pin:'<path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2"/>',sliders:'<path d="M4 21v-7M4 10V3M12 21v-9M12 8V3M20 21v-5M20 12V3M1 14h6M9 8h6M17 16h6"/>',thermometer:'<path d="M14 14.8V5a4 4 0 0 0-8 0v9.8a6 6 0 1 0 8 0Z"/><path d="M10 9v8"/>',droplet:'<path d="M12 2.7S5 10 5 15a7 7 0 0 0 14 0c0-5-7-12.3-7-12.3Z"/>',lightbulb:'<path d="M9 18h6M10 22h4M8 14a7 7 0 1 1 8 0c-1.3.8-1 2-1 2H9s.3-1.2-1-2Z"/>',lock:'<rect x="4" y="10" width="16" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/>',sparkles:'<path d="m12 3 1.1 3.2L16 8l-2.9 1.8L12 13l-1.1-3.2L8 8l2.9-1.8L12 3ZM5 14l.8 2.2L8 17.5l-2.2 1.3L5 21l-.8-2.2L2 17.5l2.2-1.3L5 14ZM19 12l.8 2.2 2.2 1.3-2.2 1.3L19 19l-.8-2.2-2.2-1.3 2.2-1.3L19 12Z"/>',film:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="M7 5v14M17 5v14M3 9h4M17 9h4M3 15h4M17 15h4"/>',moon:'<path d="M21 12.8A9 9 0 1 1 11.2 3 7 7 0 0 0 21 12.8Z"/>',shield:'<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Z"/>',server:'<rect x="3" y="4" width="18" height="6" rx="2"/><rect x="3" y="14" width="18" height="6" rx="2"/><path d="M7 7h.01M7 17h.01"/>',cloud:'<path d="M17.5 19H6a4 4 0 0 1-.7-7.94A7 7 0 0 1 19 9.5a4.75 4.75 0 0 1-1.5 9.5Z"/>',key:'<circle cx="8" cy="15" r="4"/><path d="m11 12 9-9M18 5l2 2M15 8l2 2"/>',logOut:'<path d="M10 17l5-5-5-5M15 12H3M15 3h5a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1h-5"/>'};
const svg=n=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${iconPaths[n]||iconPaths.apps}</svg>`;
const attr=value=>String(value||'').replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const faviconUrl=url=>{try{return new URL('/favicon.ico',url).href}catch{return ''}};
if(window.crypto?.getRandomValues&&!window.crypto.randomUUID){Object.defineProperty(window.crypto,'randomUUID',{value:()=>{const bytes=window.crypto.getRandomValues(new Uint8Array(16));bytes[6]=(bytes[6]&15)|64;bytes[8]=(bytes[8]&63)|128;const hex=[...bytes].map(byte=>byte.toString(16).padStart(2,'0'));return `${hex.slice(0,4).join('')}-${hex.slice(4,6).join('')}-${hex.slice(6,8).join('')}-${hex.slice(8,10).join('')}-${hex.slice(10).join('')}`}})}
document.querySelectorAll('[data-icon]').forEach(el=>el.innerHTML=svg(el.dataset.icon));

const apps=[
 {name:'Jellyfin',type:'Media server',color:'#7759b7',mark:'J',url:'#'}, {name:'Sonarr',type:'TV management',color:'#4d91bd',mark:'S',url:'#'},
 {name:'Radarr',type:'Movie management',color:'#d7a943',mark:'R',url:'#'}, {name:'Home Assistant',type:'Smart home',color:'#42a6d5',mark:'H',url:'#'},
 {name:'Vaultwarden',type:'Password manager',color:'#233346',mark:'V',url:'#'}, {name:'Immich',type:'Photo library',color:'#df705f',mark:'I',url:'#'},
 {name:'Paperless',type:'Documents',color:'#4e9a70',mark:'P',url:'#'}, {name:'Grafana',type:'Monitoring',color:'#e08c3b',mark:'G',url:'#'}
];
const savedSettings=JSON.parse(localStorage.getItem('haven-settings')||'{}');
if(savedSettings.haToken||savedSettings.haUrl){delete savedSettings.haToken;delete savedSettings.haUrl;localStorage.setItem('haven-settings',JSON.stringify(savedSettings))}
apps.forEach(app=>{if(savedSettings.apps?.[app.name])app.url=savedSettings.apps[app.name]});
(Array.isArray(savedSettings.customApps)?savedSettings.customApps:[]).forEach(app=>{if(app?.name&&app?.url)apps.push({name:String(app.name),type:'Web application',color:'#52645c',mark:String(app.name).slice(0,1).toUpperCase(),url:String(app.url),custom:true,id:String(app.id||app.name)})});
const movies=[
 {title:'Dune: Part Two',meta:'2024 · 2h 46m',rating:'★ 8.6',poster:'linear-gradient(150deg,#c8905f,#593d33)'},
 {title:'Civil War',meta:'2024 · 1h 49m',rating:'★ 7.4',poster:'linear-gradient(150deg,#77939b,#233b3b)'},
 {title:'The Fall Guy',meta:'2024 · 2h 6m',rating:'★ 7.1',poster:'linear-gradient(150deg,#e7ad59,#a43d30)'}
];
function appCard(app){const favicon=faviconUrl(app.url),logo=favicon?`<img src="${attr(favicon)}" alt="">`:'';return `<button class="app-tile" data-app="${attr(app.name)}" data-url="${attr(app.url)}"><span class="app-logo" style="background:${app.color}">${logo}<b>${attr(app.mark)}</b></span><span class="app-meta"><strong>${attr(app.name)}</strong><small>${attr(app.type)}</small></span><i class="online-dot"></i></button>`}
const wireLogoFallbacks=()=>document.querySelectorAll('.app-logo img,.custom-app-list img').forEach(img=>img.addEventListener('error',()=>img.remove(),{once:true}));
function renderApps(){document.querySelector('#favorite-apps').innerHTML=apps.filter(app=>app.url&&app.url!=='#').slice(0,5).map(appCard).join('');document.querySelector('#all-apps').innerHTML=apps.map(appCard).join('');wireLogoFallbacks()}
renderApps();
document.querySelector('#movie-list').innerHTML=movies.map(m=>`<div class="movie"><div class="poster" style="background:${m.poster}">${m.title}</div><div><strong>${m.title}</strong><small>${m.meta}</small><small class="rating">${m.rating}</small></div></div>`).join('');

document.querySelector('#settings-content').innerHTML=`
  <div class="auth-panel"><span class="integration-logo">${svg('key')}</span><div><strong>Keycloak authentication</strong><small id="auth-status">Demo mode · configured at deployment</small></div><button class="connect-btn" data-logout>Sign out</button></div>
  <div class="settings-layout">
    <form class="settings-panel apps-settings" id="keycloak-settings"><div class="settings-title"><span class="integration-logo">${svg('key')}</span><div><h2>Keycloak authentication</h2><p>Configure sign-in for every Haven device</p></div></div><div class="url-grid"><label>Keycloak URL<input name="url" type="url" placeholder="https://auth.example.com"></label><label>Realm<input name="realm" placeholder="home"></label><label>Client ID<input name="clientId" placeholder="haven" value="haven"></label><label>Haven setup token<input name="setupToken" type="password" autocomplete="off" placeholder="From your Portainer stack"></label></div><label class="toggle-label"><input name="enabled" type="checkbox"> Require Keycloak login</label><div class="form-actions"><button class="primary-button" type="submit">Save authentication</button></div><small class="privacy-note">The setup token authorizes this change but is never saved by the browser. Reloading after enablement will send everyone through Keycloak.</small></form>
    <form class="settings-panel" id="general-settings"><div class="settings-title"><span class="integration-logo">${svg('cloud')}</span><div><h2>Dashboard</h2><p>Personalize this device</p></div></div><label>Weather location<input name="weatherLocation" value="${attr(savedSettings.weatherLocation||'San Francisco, CA')}" placeholder="City, State or ZIP"></label><label>Display name<input name="displayName" value="${attr(savedSettings.displayName||'Mike')}" placeholder="Your name"></label><button class="primary-button" type="submit">Save dashboard</button></form>
    <div class="settings-panel" id="ha-settings"><div class="settings-title"><span class="integration-logo">${svg('home')}</span><div><h2>Home Assistant</h2><p>Server-managed secure integration</p></div></div><div class="managed-integration"><span class="managed-dot" id="ha-status-dot"></span><div><strong id="ha-status-label">Checking configuration…</strong><small>URL and token are stored only in Portainer</small></div></div><button class="outline-button" type="button" id="test-ha">Test connection</button><small class="privacy-note">Configure HOME_ASSISTANT_URL and HOME_ASSISTANT_TOKEN in the Portainer stack. Haven validates your Keycloak session before proxying requests.</small></div>
    <form class="settings-panel apps-settings" id="apps-settings"><div class="settings-title"><span class="integration-logo">${svg('apps')}</span><div><h2>Application URLs</h2><p>Add services and automatically use their favicon</p></div></div><div class="url-grid">${apps.filter(app=>!app.custom).map(app=>`<label>${attr(app.name)}<input data-app-url="${attr(app.name)}" type="url" value="${attr(app.url==='#'?'':app.url)}" placeholder="https://${app.name.toLowerCase().replace(' ','-')}.example.com"></label>`).join('')}</div><div class="custom-app-list">${apps.filter(app=>app.custom).map(app=>`<div><span>${faviconUrl(app.url)?`<img src="${attr(faviconUrl(app.url))}" alt="">`:''}<strong>${attr(app.name)}</strong><small>${attr(app.url)}</small></span><button type="button" class="remove-app" data-remove-app="${attr(app.id)}">Remove</button></div>`).join('')}</div><div class="add-app-row"><label>Application name<input name="newAppName" placeholder="Proxmox"></label><label>Application URL<input name="newAppUrl" type="url" placeholder="https://proxmox.example.com"></label><button class="outline-button" type="button" id="add-app">Add application</button></div><div class="form-actions"><button class="primary-button" type="submit">Save app links</button></div></form>
    <div class="settings-panel install-panel"><div class="settings-title"><span class="integration-logo">${svg('apps')}</span><div><h2>Install Haven</h2><p>Use it like a native app</p></div></div><p>Add Haven to your phone's home screen for a full-screen experience and offline access to the dashboard shell.</p><button class="primary-button" id="settings-install" type="button">Install on this device</button><small class="privacy-note" id="install-help">On iPhone: Share → Add to Home Screen.</small></div>
  </div>`;
wireLogoFallbacks();

function showPage(name){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===`page-${name}`));document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.page===name));document.querySelector('.sidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page)));
document.querySelectorAll('[data-page-target]').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.pageTarget)));
document.querySelectorAll('[data-open-settings]').forEach(b=>b.addEventListener('click',()=>showPage('settings')));
document.querySelector('#mobile-menu').addEventListener('click',()=>document.querySelector('.sidebar').classList.toggle('open'));
const toast=msg=>{const t=document.querySelector('#toast');t.querySelector('p').textContent=msg;t.classList.add('show');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>t.classList.remove('show'),2800)};
document.addEventListener('click',e=>{const app=e.target.closest('[data-app]');if(app){if(app.dataset.url==='#')toast(`Add the ${app.dataset.app} URL in Settings`);else window.open(app.dataset.url,'_blank','noopener')}const scene=e.target.closest('[data-scene]');if(scene)toast(`${scene.dataset.scene} scene activated`)});
const saveSettings=patch=>{Object.assign(savedSettings,patch);localStorage.setItem('haven-settings',JSON.stringify(savedSettings))};
document.querySelector('#general-settings').addEventListener('submit',e=>{e.preventDefault();const data=new FormData(e.currentTarget);const weatherLocation=data.get('weatherLocation').trim(),displayName=data.get('displayName').trim();saveSettings({weatherLocation,displayName});document.querySelector('.weather-place').innerHTML=`${svg('pin')} ${weatherLocation}`;document.querySelector('#welcome-name').textContent=displayName;document.querySelector('#sidebar-name').textContent=displayName;toast('Dashboard settings saved')});
document.querySelector('#apps-settings').addEventListener('submit',e=>{e.preventDefault();const urls={};e.currentTarget.querySelectorAll('[data-app-url]').forEach(input=>urls[input.dataset.appUrl]=input.value.trim());saveSettings({apps:urls});toast('Application links saved');setTimeout(()=>location.reload(),400)});
document.querySelector('#add-app').addEventListener('click',()=>{const form=document.querySelector('#apps-settings'),name=form.elements.newAppName.value.trim(),rawUrl=form.elements.newAppUrl.value.trim();if(!name||!rawUrl){toast('Enter an application name and URL');return}let url;try{url=new URL(rawUrl);if(!['http:','https:'].includes(url.protocol))throw new Error()}catch{toast('Enter a valid http or https URL');return}const customApps=Array.isArray(savedSettings.customApps)?savedSettings.customApps:[];customApps.push({id:window.crypto?.randomUUID?.()||`${Date.now()}`,name,url:url.href.replace(/\/$/,'')});saveSettings({customApps});toast(`${name} added`);setTimeout(()=>location.reload(),500)});
document.querySelectorAll('[data-remove-app]').forEach(button=>button.addEventListener('click',()=>{const customApps=(Array.isArray(savedSettings.customApps)?savedSettings.customApps:[]).filter(app=>String(app.id||app.name)!==button.dataset.removeApp);saveSettings({customApps});toast('Application removed');setTimeout(()=>location.reload(),400)}));
document.querySelector('#keycloak-settings').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget,data=new FormData(form),payload={enabled:data.get('enabled')==='on',url:data.get('url').trim(),realm:data.get('realm').trim(),clientId:data.get('clientId').trim()};const setupToken=data.get('setupToken');if(!setupToken){toast('Enter the Haven setup token from Portainer');return}try{const response=await fetch('/api/setup/keycloak',{method:'POST',headers:{'Content-Type':'application/json','X-Haven-Setup-Token':setupToken},body:JSON.stringify(payload)}),result=await response.json();if(!response.ok){toast(result.error||'Authentication settings were rejected');return}toast('Keycloak settings saved — starting sign-in');setTimeout(()=>location.replace(`${location.origin}${location.pathname}`),900)}catch{toast('Could not save authentication settings')}});
fetch('/api/integrations').then(r=>r.json()).then(status=>{if(status.version)document.querySelector('#version-badge').textContent=`v${status.version}`;const auth=status.keycloak||{},form=document.querySelector('#keycloak-settings');form.elements.url.value=auth.url||'';form.elements.realm.value=auth.realm||'';form.elements.clientId.value=auth.clientId||'haven';form.elements.enabled.checked=Boolean(auth.enabled);document.querySelector('#auth-status').textContent=auth.configured?`Connected to ${auth.realm}`:'Not configured · use Settings below';const configured=status.homeAssistant?.configured;document.querySelector('#ha-status-label').textContent=configured?'Configured in Portainer':'Not configured';document.querySelector('#ha-status-dot').classList.toggle('connected',configured)}).catch(()=>document.querySelector('#ha-status-label').textContent='Server status unavailable');
document.querySelector('#test-ha').addEventListener('click',async()=>{if(!window.havenAccessToken){toast('Enable Keycloak before testing Home Assistant');return}try{const response=await fetch('/api/home-assistant/api/',{headers:{Authorization:`Bearer ${window.havenAccessToken}`}});toast(response.ok?'Home Assistant connected':response.status===503?'Configure Home Assistant in Portainer':'Connection rejected')}catch{toast('Could not reach the Haven integration API')}});
const search=document.querySelector('#search');search.addEventListener('input',()=>{const q=search.value.toLowerCase();document.querySelectorAll('.app-tile').forEach(el=>el.style.display=el.dataset.app.toLowerCase().includes(q)?'flex':'none')});
document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();search.focus()}if(e.key==='Escape')search.blur()});
const now=new Date();document.querySelector('#today-label').textContent=now.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric'});const hour=now.getHours();document.querySelector('.welcome-row h1').firstChild.textContent=`Good ${hour<12?'morning':hour<17?'afternoon':'evening'}, `;
if(savedSettings.weatherLocation)document.querySelector('.weather-place').innerHTML=`${svg('pin')} ${savedSettings.weatherLocation}`;

let installPrompt=null;const installButtons=[document.querySelector('#install-app'),document.querySelector('#settings-install')];window.addEventListener('beforeinstallprompt',event=>{event.preventDefault();installPrompt=event;document.querySelector('#install-app').classList.remove('hidden')});installButtons.forEach(button=>button?.addEventListener('click',async()=>{if(!installPrompt){toast('Use your browser menu to add Haven to the home screen');return}await installPrompt.prompt();installPrompt=null;document.querySelector('#install-app').classList.add('hidden')}));window.addEventListener('appinstalled',()=>toast('Haven installed successfully'));
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/service-worker.js').catch(error=>console.warn('Service worker registration failed',error)));

async function start(){let config={auth:{enabled:false},user:{name:'Mike'}};try{config={...config,...(await import('./config.js')).default}}catch{}const app=document.querySelector('#app'),login=document.querySelector('#login-screen');let keycloak=null;const enter=(profile={})=>{const name=profile.firstName||profile.given_name||profile.name||config.user?.name||'there';document.querySelector('#welcome-name').textContent=name;document.querySelector('#sidebar-name').textContent=name;document.querySelectorAll('.avatar').forEach(a=>a.textContent=name.slice(0,2).toUpperCase());login.classList.add('hidden');app.classList.remove('hidden')};document.querySelectorAll('[data-logout]').forEach(button=>button.addEventListener('click',async()=>{button.disabled=true;window.havenAccessToken=null;if(keycloak){try{await keycloak.logout({redirectUri:`${location.origin}${location.pathname}`});return}catch(error){console.error('Keycloak logout failed',error)}}location.replace(`${location.origin}${location.pathname}`)}));if(new URLSearchParams(location.search).has('setup')){enter();showPage('settings');toast('Recovery mode — update or disable Keycloak below');return}if(!config.auth?.enabled){enter();return}login.classList.remove('hidden');const connect=async()=>{try{const {default:Keycloak}=await import(config.auth.adapterUrl||'https://cdn.jsdelivr.net/npm/keycloak-js/+esm');keycloak=new Keycloak({url:config.auth.url,realm:config.auth.realm,clientId:config.auth.clientId});const ok=await keycloak.init({onLoad:'login-required',pkceMethod:window.isSecureContext?'S256':false,checkLoginIframe:false});if(ok){window.havenAccessToken=keycloak.token;setInterval(()=>keycloak.updateToken(60).then(()=>window.havenAccessToken=keycloak.token).catch(()=>keycloak.login()),30000);document.querySelector('#auth-status').textContent=`Connected to ${config.auth.realm}`;enter(keycloak.tokenParsed)}}catch(err){console.error(err);login.classList.remove('hidden');const message=err?.message||String(err);const errorBox=document.querySelector('#auth-error');errorBox.textContent=message;errorBox.classList.remove('hidden');toast('Could not reach Keycloak. Open authentication settings to recover.')}};document.querySelector('#login-button').onclick=connect;await connect()}
start().then(()=>{if(savedSettings.displayName){document.querySelector('#welcome-name').textContent=savedSettings.displayName;document.querySelector('#sidebar-name').textContent=savedSettings.displayName}});
