import { cachedUserJson, requestOrQueue } from './offline-data.js';

const escapeHtml=value=>String(value||'').replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;').replaceAll('>','&gt;');
const authHeaders=()=>window.havenAccessToken?{Authorization:`Bearer ${window.havenAccessToken}`}:{ };
export const localDateKey=date=>`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
let selectedDate=localDateKey(new Date()),notify=()=>{};

function taskMarkup(task,compact=false){const repeat={daily:'Every day',weekdays:'Weekdays',weekly:'Weekly',monthly:'Monthly'}[task.recurrence]||'',meta=[task.time?new Date(`2000-01-01T${task.time}`).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):'',repeat].filter(Boolean).join(' · ');return `<div class="daily-task${task.done?' done':''}" data-daily-task="${escapeHtml(task.id)}"><button type="button" class="daily-check" data-daily-toggle="${escapeHtml(task.id)}" data-occurrence-date="${escapeHtml(task.occurrenceDate||task.date)}" data-done="${task.done?'false':'true'}" aria-label="${task.done?'Mark incomplete':'Complete task'}">${task.done?'✓':''}</button><span><strong>${escapeHtml(task.title)}</strong>${meta?`<small>${escapeHtml(meta)}</small>`:''}</span>${compact?'':`<button type="button" class="daily-delete" data-daily-delete="${escapeHtml(task.id)}" data-recurring="${task.recurrence!=='none'}" aria-label="Delete task">×</button>`}</div>`}
async function fetchTasks(date){const result=await cachedUserJson(`daily-tasks:${date}`,async()=>{const response=await fetch(`/api/daily-tasks?date=${encodeURIComponent(date)}`,{headers:authHeaders(),cache:'no-store'}),data=await response.json();if(!response.ok)throw new Error(data.error||'Daily planner unavailable');return data.tasks||[]});return result}

export async function loadDailyPlanner(){const input=document.querySelector('#daily-date'),list=document.querySelector('#daily-task-list');input.value=selectedDate;try{const result=await fetchTasks(selectedDate),tasks=result.data;list.innerHTML=(result.stale?'<div class="calendar-cache-note">Offline · showing the last saved plan</div>':'')+(tasks.length?tasks.sort((a,b)=>(a.done-b.done)||(a.time||'99:99').localeCompare(b.time||'99:99')).map(task=>taskMarkup(task)).join(''):'<div class="empty-state daily-empty"><h2>Nothing planned</h2><p>Add the small things you need to get done this day.</p></div>')}catch(error){list.innerHTML=`<div class="integration-empty">${escapeHtml(error.message)}</div>`}}
export async function loadDailyWidget(){const list=document.querySelector('#daily-widget-list');try{const result=await fetchTasks(localDateKey(new Date())),tasks=result.data,open=tasks.filter(task=>!task.done);list.innerHTML=open.length?open.slice(0,4).map(task=>taskMarkup(task,true)).join(''):`<div class="integration-empty">${tasks.length?'Everything is done for today.':'Nothing planned for today.'}</div>`;list.closest('[data-widget]')?.classList.toggle('offline-widget',result.stale)}catch{list.innerHTML='<div class="integration-empty">Daily planner unavailable.</div>'}}

export function initializeDailyPlanner(options={}){notify=options.toast||notify;
  document.querySelector('#daily-task-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,data=new FormData(form),title=String(data.get('title')||'').trim();if(!title)return;try{const response=await requestOrQueue('/api/daily-tasks',{method:'POST',headers:{'Content-Type':'application/json',...authHeaders()},body:JSON.stringify({title,date:selectedDate,time:data.get('time'),recurrence:data.get('recurrence')})},'daily task'),result=await response.json();if(!response.ok)throw new Error(result.error);form.reset();if(result.queued){notify('Task queued and will sync when Haven is online');return}await Promise.all([loadDailyPlanner(),loadDailyWidget()])}catch(error){notify(error.message||'Task could not be added')}});
  document.addEventListener('click',async event=>{const toggle=event.target.closest('[data-daily-toggle]'),remove=event.target.closest('[data-daily-delete]');if(!toggle&&!remove)return;if(remove?.dataset.recurring==='true'&&!confirm('Delete this entire repeating task series?'))return;const id=toggle?.dataset.dailyToggle||remove?.dataset.dailyDelete;try{const response=await requestOrQueue('/api/daily-tasks',{method:remove?'DELETE':'PATCH',headers:{'Content-Type':'application/json',...authHeaders()},body:JSON.stringify({id,date:toggle?.dataset.occurrenceDate||selectedDate,...(toggle?{done:toggle.dataset.done==='true'}:{})})},remove?'daily task deletion':'daily task update'),data=await response.json();if(!response.ok)throw new Error(data.error);if(data.queued){notify('Change queued and will sync when Haven is online');return}await Promise.all([loadDailyPlanner(),loadDailyWidget()])}catch(error){notify(error.message||'Task could not be updated')}});
  document.querySelector('#daily-date').addEventListener('change',event=>{selectedDate=event.target.value||localDateKey(new Date());loadDailyPlanner()});
  document.querySelector('#daily-prev').addEventListener('click',()=>{const date=new Date(`${selectedDate}T12:00:00`);date.setDate(date.getDate()-1);selectedDate=localDateKey(date);loadDailyPlanner()});
  document.querySelector('#daily-next').addEventListener('click',()=>{const date=new Date(`${selectedDate}T12:00:00`);date.setDate(date.getDate()+1);selectedDate=localDateKey(date);loadDailyPlanner()});
  document.querySelector('#daily-today').addEventListener('click',()=>{selectedDate=localDateKey(new Date());loadDailyPlanner()});
}
