import { createServer } from 'node:http';
import { readFile, stat, writeFile, mkdir, rename } from 'node:fs/promises';
import { extname, join, normalize } from 'node:path';
import { createPublicKey, verify as verifySignature, createCipheriv, createDecipheriv, randomBytes, scryptSync } from 'node:crypto';

const port = Number(process.env.PORT || 3000);
const version = process.env.HAVEN_VERSION || '0.8.0';
const publicDir = process.env.PUBLIC_DIR || '/app/public';
const dataDir = process.env.DATA_DIR || '/app/data';
const settingsFile = join(dataDir,'settings.json');
const setupToken = process.env.HAVEN_SETUP_TOKEN || '';
const authBypass = String(process.env.HAVEN_AUTH_BYPASS).toLowerCase()==='true';
const hostLanIp = String(process.env.HAVEN_HOST_IP||'').trim();
const baseAuth = {enabled:String(process.env.KEYCLOAK_ENABLED).toLowerCase()==='true',url:(process.env.KEYCLOAK_URL||'').replace(/\/$/,''),realm:process.env.KEYCLOAK_REALM||'',clientId:process.env.KEYCLOAK_CLIENT_ID||'haven'};
const emptyIntegrations = {homeAssistant:{url:(process.env.HOME_ASSISTANT_URL||'').replace(/\/$/,''),token:process.env.HOME_ASSISTANT_TOKEN||'',calendarEntity:'',whiskerEntity:'',quickActions:[]},plex:{url:'',token:''},shelfLife:{url:'',apiKey:''},vikunja:{url:'',token:''},chores:{url:''},calendar:{icsUrl:''},arrs:{sonarr:{url:'',apiKey:''},radarr:{url:'',apiKey:''},lidarr:{url:'',apiKey:''},readarr:{url:'',apiKey:''}}};
let storedSettings = {};
await mkdir(dataDir,{recursive:true});
try{storedSettings=JSON.parse(await readFile(settingsFile,'utf8'))}catch{}
let runtimeAuth = {...baseAuth,...(storedSettings.auth||{})};
// Shared household services are editable by any authenticated Keycloak user.
let integrationOwnerSub = '';
let userPreferences = storedSettings.userPreferences&&typeof storedSettings.userPreferences==='object'?storedSettings.userPreferences:{};
function normalizeApplications(items){return (Array.isArray(items)?items:[]).slice(0,100).map((item,index)=>{try{const url=cleanUrl(item?.url);if(!url)return null;let icon='';try{const candidate=String(item?.icon||'').trim();icon=candidate?cleanUrl(candidate):''}catch{}return {id:String(item?.id||`app-${index}`).slice(0,100),name:String(item?.name||'Application').trim().slice(0,80),url,icon}}catch{return null}}).filter(Boolean)}
let applications = normalizeApplications(storedSettings.applications);
let dashboard = {weatherLocation:String(storedSettings.dashboard?.weatherLocation||'San Francisco, CA').slice(0,120),displayName:String(storedSettings.dashboard?.displayName||'Mike').slice(0,80),revision:Number(storedSettings.dashboard?.revision||0)};
let integrations = {homeAssistant:{...emptyIntegrations.homeAssistant,...(storedSettings.integrations?.homeAssistant||{})},plex:{...emptyIntegrations.plex,...(storedSettings.integrations?.plex||{})},shelfLife:{...emptyIntegrations.shelfLife,...(storedSettings.integrations?.shelfLife||{})},vikunja:{...emptyIntegrations.vikunja,...(storedSettings.integrations?.vikunja||{})},chores:{...emptyIntegrations.chores,...(storedSettings.integrations?.chores||{})},calendar:{...emptyIntegrations.calendar,...(storedSettings.integrations?.calendar||{})},arrs:{}};
if(integrations.homeAssistant.calendarEntity&&!integrations.homeAssistant.calendarEntity.startsWith('calendar.'))integrations.homeAssistant.calendarEntity=`calendar.${integrations.homeAssistant.calendarEntity}`;
for(const name of Object.keys(emptyIntegrations.arrs))integrations.arrs[name]={...emptyIntegrations.arrs[name],...(storedSettings.integrations?.arrs?.[name]||{})};
const mime = {'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.webmanifest':'application/manifest+json','.svg':'image/svg+xml','.png':'image/png'};
const clientConfig = {user:{name:process.env.HAVEN_USER_NAME||'Mike'},auth:{}};

let persistQueue=Promise.resolve();
async function persistSettings(){storedSettings={...storedSettings,auth:runtimeAuth,integrations,applications,dashboard,userPreferences,integrationOwnerSub};const payload=JSON.stringify(storedSettings,null,2),temporaryFile=`${settingsFile}.tmp`;persistQueue=persistQueue.catch(()=>{}).then(async()=>{await writeFile(temporaryFile,payload,'utf8');await rename(temporaryFile,settingsFile)});return persistQueue}
async function writeClientConfig(){clientConfig.auth={...runtimeAuth,enabled:runtimeAuth.enabled&&!authBypass,adapterUrl:'/vendor/keycloak.js'};await writeFile(join(publicDir,'config.js'),`export default ${JSON.stringify(clientConfig)};\n`,'utf8')}
await writeClientConfig();

function securityHeaders(){
  let keycloakOrigin='';
  try{keycloakOrigin=runtimeAuth.url?new URL(runtimeAuth.url).origin:''}catch{}
  return {'X-Content-Type-Options':'nosniff','X-Frame-Options':'SAMEORIGIN','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(), microphone=(), geolocation=()','Content-Security-Policy':`default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https: ${keycloakOrigin}; img-src 'self' data: blob: http: https:; frame-ancestors 'self'`};
}
function send(res,status,body,type='application/json'){res.writeHead(status,{...securityHeaders(),'Content-Type':type,'Cache-Control':'no-store'});res.end(type==='application/json'&&typeof body!=='string'?JSON.stringify(body):body)}
async function readJson(req){let body='';for await(const chunk of req){body+=chunk;if(body.length>65536)throw new Error('Request too large')}return JSON.parse(body||'{}')}
async function readBuffer(req,limit=5*1024*1024){const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>limit)throw new Error('Backup is too large');chunks.push(chunk)}return Buffer.concat(chunks)}
function setupAuthorized(req,res){if(!setupToken){send(res,503,{error:'HAVEN_SETUP_TOKEN is not configured in Portainer'});return false}if(req.headers['x-haven-setup-token']!==setupToken){send(res,403,{error:'Invalid setup token'});return false}return true}
function cleanUrl(value){const text=String(value||'').trim().replace(/\/$/,'');if(!text)return '';const parsed=new URL(text);if(!['http:','https:'].includes(parsed.protocol))throw new Error('Only http and https URLs are allowed');return text}

const jwksCache=new Map();
const decodeJwtPart=value=>JSON.parse(Buffer.from(value,'base64url').toString('utf8'));
async function realmKeys(issuer,refresh=false){const cached=jwksCache.get(issuer);if(!refresh&&cached&&cached.expires>Date.now())return cached.keys;const response=await fetch(`${issuer}/protocol/openid-connect/certs`,{signal:AbortSignal.timeout(8000)});if(!response.ok)throw new Error(`Keycloak certificates returned ${response.status}`);const keys=(await response.json()).keys||[];jwksCache.set(issuer,{keys,expires:Date.now()+300000});return keys}
async function authenticatedIdentity(req){
  if(!runtimeAuth.enabled||!runtimeAuth.url||!runtimeAuth.realm)return false;
  const authorization=req.headers.authorization;if(!authorization?.startsWith('Bearer '))return false;
  try{const token=authorization.slice(7),parts=token.split('.');if(parts.length!==3)return false;const header=decodeJwtPart(parts[0]),claims=decodeJwtPart(parts[1]),issuer=`${runtimeAuth.url}/realms/${runtimeAuth.realm}`;if(header.alg!=='RS256'||!header.kid||!claims.sub||Number(claims.exp||0)*1000<=Date.now())return false;let keys=await realmKeys(issuer),jwk=keys.find(key=>key.kid===header.kid&&key.kty==='RSA');if(!jwk){keys=await realmKeys(issuer,true);jwk=keys.find(key=>key.kid===header.kid&&key.kty==='RSA')}if(!jwk)return false;const valid=verifySignature('RSA-SHA256',Buffer.from(`${parts[0]}.${parts[1]}`),createPublicKey({key:jwk,format:'jwk'}),Buffer.from(parts[2],'base64url'));return valid?claims:false}catch(error){console.warn('Keycloak token verification failed',error.message);return false}
}
async function authenticated(req){return await authenticatedIdentity(req)}
async function requireAuth(req,res){if(await authenticated(req))return true;send(res,401,{error:'Keycloak authentication required'});return false}
async function integrationOwnerAuthorized(req,res){const identity=await authenticatedIdentity(req);if(identity?.sub&&(!integrationOwnerSub||integrationOwnerSub===identity.sub)){if(!integrationOwnerSub){integrationOwnerSub=identity.sub;await persistSettings()}return true}return setupAuthorized(req,res)}

async function configureKeycloak(req,res){
  if(!setupAuthorized(req,res))return;
  try{const body=await readJson(req),url=cleanUrl(body.url),realm=String(body.realm||'').trim(),clientId=String(body.clientId||'').trim();if(body.enabled&&(!url||!realm||!clientId))return send(res,400,{error:'URL, realm, and client ID are required'});runtimeAuth={enabled:Boolean(body.enabled),url,realm,clientId:clientId||'haven'};await persistSettings();await writeClientConfig();return send(res,200,{ok:true})}catch(error){return send(res,400,{error:error.message||'Invalid settings'})}
}
async function applicationsApi(req,res){const identity=await authenticatedIdentity(req);if(!identity)return send(res,401,{error:'Keycloak authentication required'});if(req.method==='GET')return send(res,200,{applications});if(req.method==='PUT'){try{const body=await readJson(req);applications=normalizeApplications(body.applications);await persistSettings();return send(res,200,{ok:true,applications})}catch(error){return send(res,400,{error:error.message||'Invalid applications'})}}return send(res,405,{error:'Method not allowed'})}
const backupKey=()=>setupToken?scryptSync(setupToken,'haven-backup-v1',32):null;
async function backupApi(req,res){
  if(!await requireAuth(req,res))return;
  const key=backupKey();if(!key)return send(res,503,{error:'Configure HAVEN_SETUP_TOKEN before using encrypted backups'});
  try{
    if(req.method==='GET'){
      await persistSettings();const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key,iv),plaintext=Buffer.from(JSON.stringify(storedSettings)),encrypted=Buffer.concat([cipher.update(plaintext),cipher.final()]),tag=cipher.getAuthTag(),body=Buffer.concat([Buffer.from('HAVEN1'),iv,tag,encrypted]);
      res.writeHead(200,{...securityHeaders(),'Content-Type':'application/octet-stream','Content-Disposition':`attachment; filename="haven-backup-${new Date().toISOString().slice(0,10)}.haven"`,'Cache-Control':'no-store'});return res.end(body);
    }
    if(req.method==='POST'){
      const body=await readBuffer(req);if(body.subarray(0,6).toString()!=='HAVEN1'||body.length<35)throw new Error('Not a Haven encrypted backup');const iv=body.subarray(6,18),tag=body.subarray(18,34),encrypted=body.subarray(34),decipher=createDecipheriv('aes-256-gcm',key,iv);decipher.setAuthTag(tag);const restored=JSON.parse(Buffer.concat([decipher.update(encrypted),decipher.final()]).toString('utf8'));if(!restored||typeof restored!=='object'||Array.isArray(restored))throw new Error('Backup contents are invalid');
      runtimeAuth={...baseAuth,...(restored.auth||{})};applications=normalizeApplications(restored.applications);dashboard={...dashboard,...(restored.dashboard||{})};userPreferences=restored.userPreferences&&typeof restored.userPreferences==='object'?restored.userPreferences:{};integrations={homeAssistant:{...emptyIntegrations.homeAssistant,...(restored.integrations?.homeAssistant||{})},plex:{...emptyIntegrations.plex,...(restored.integrations?.plex||{})},shelfLife:{...emptyIntegrations.shelfLife,...(restored.integrations?.shelfLife||{})},vikunja:{...emptyIntegrations.vikunja,...(restored.integrations?.vikunja||{})},chores:{...emptyIntegrations.chores,...(restored.integrations?.chores||{})},calendar:{...emptyIntegrations.calendar,...(restored.integrations?.calendar||{})},arrs:{}};for(const name of Object.keys(emptyIntegrations.arrs))integrations.arrs[name]={...emptyIntegrations.arrs[name],...(restored.integrations?.arrs?.[name]||{})};storedSettings=restored;await persistSettings();await writeClientConfig();return send(res,200,{ok:true});
    }
    return send(res,405,{error:'Method not allowed'});
  }catch(error){return send(res,400,{error:error.message==='Unsupported state or unable to authenticate data'?'Backup key does not match this Haven installation':error.message||'Backup operation failed'})}
}
async function dashboardApi(req,res){if(!await requireAuth(req,res))return;if(req.method==='GET')return send(res,200,dashboard);if(req.method==='PUT'){try{const body=await readJson(req);dashboard={weatherLocation:String(body.weatherLocation||'San Francisco, CA').trim().slice(0,120),displayName:String(body.displayName||'Mike').trim().slice(0,80),revision:Date.now()};await persistSettings();return send(res,200,dashboard)}catch(error){return send(res,400,{error:error.message||'Invalid dashboard settings'})}}return send(res,405,{error:'Method not allowed'})}
function normalizeDailyTasks(items){return (Array.isArray(items)?items:[]).slice(-500).map(item=>({id:String(item?.id||''),title:String(item?.title||'').trim().slice(0,160),date:/^\d{4}-\d{2}-\d{2}$/.test(String(item?.date||''))?String(item.date):'',time:/^\d{2}:\d{2}$/.test(String(item?.time||''))?String(item.time):'',done:Boolean(item?.done),createdAt:String(item?.createdAt||'')})).filter(item=>item.id&&item.title&&item.date)}
async function dailyTasksApi(req,res,url){const identity=await authenticatedIdentity(req);if(!identity)return send(res,401,{error:'Keycloak authentication required'});try{const prefs=userPreferences[identity.sub]||{},tasks=normalizeDailyTasks(prefs.dailyTasks),date=String(url.searchParams.get('date')||'');if(req.method==='GET')return send(res,200,{tasks:date?tasks.filter(task=>task.date===date):tasks});const body=await readJson(req);if(req.method==='POST'){const task=normalizeDailyTasks([{id:randomBytes(12).toString('hex'),title:body.title,date:body.date,time:body.time,done:false,createdAt:new Date().toISOString()}])[0];if(!task)return send(res,400,{error:'Task title and date are required'});tasks.push(task);userPreferences[identity.sub]={...prefs,dailyTasks:tasks};await persistSettings();return send(res,201,task)}const index=tasks.findIndex(task=>task.id===String(body.id||''));if(index<0)return send(res,404,{error:'Daily task not found'});if(req.method==='PATCH'){tasks[index]={...tasks[index],done:Object.hasOwn(body,'done')?Boolean(body.done):tasks[index].done,title:String(body.title||tasks[index].title).trim().slice(0,160),time:Object.hasOwn(body,'time')&&/^\d{2}:\d{2}$/.test(String(body.time))?String(body.time):tasks[index].time};userPreferences[identity.sub]={...prefs,dailyTasks:tasks};await persistSettings();return send(res,200,tasks[index])}if(req.method==='DELETE'){tasks.splice(index,1);userPreferences[identity.sub]={...prefs,dailyTasks:tasks};await persistSettings();return send(res,200,{ok:true})}return send(res,405,{error:'Method not allowed'})}catch(error){return send(res,400,{error:error.message||'Daily task could not be saved'})}}
const defaultWidgets=['weather','home-status','daily-tasks','shelf-life','whisker','sentinel','applications','plex','quick-actions','vikunja','immich','chores'];
function normalizeWidgetPrefs(input){const order=[...new Set((Array.isArray(input?.order)?input.order:defaultWidgets).filter(id=>defaultWidgets.includes(id)))];for(const id of defaultWidgets)if(!order.includes(id))order.push(id);const hidden=(Array.isArray(input?.hidden)?input.hidden:[]).filter(id=>defaultWidgets.includes(id)),sizes={},wideDefaults=new Set(['applications','vikunja','chores']);for(const id of defaultWidgets)sizes[id]=['small','medium','wide'].includes(input?.sizes?.[id])?input.sizes[id]:wideDefaults.has(id)?'wide':'medium';return {order,hidden,sizes}}
async function meApi(req,res){const identity=await authenticatedIdentity(req);if(!identity)return send(res,401,{error:'Keycloak authentication required'});const current=userPreferences[identity.sub]||{},fullName=identity.name||identity.preferred_username||identity.email||'Haven user',profile={sub:identity.sub,name:identity.given_name||String(fullName).trim().split(/\s+/)[0],username:identity.preferred_username||'',email:identity.email||'',widgets:normalizeWidgetPrefs(current.widgets),favoriteAppIds:Array.isArray(current.favoriteAppIds)?current.favoriteAppIds:[],vikunjaUserId:current.vikunjaUserId??null,vikunjaRejected:Boolean(current.vikunjaRejected)};if(req.method==='GET')return send(res,200,profile);if(req.method==='PUT'){const body=await readJson(req),next={...current};if(body.widgets)next.widgets=normalizeWidgetPrefs(body.widgets);if(Array.isArray(body.favoriteAppIds))next.favoriteAppIds=[...new Set(body.favoriteAppIds.map(String))].slice(0,20);if(Object.hasOwn(body,'vikunjaUserId')){next.vikunjaUserId=body.vikunjaUserId===null?null:Number(body.vikunjaUserId);next.vikunjaRejected=Boolean(body.vikunjaRejected)}userPreferences[identity.sub]=next;await persistSettings();return send(res,200,{...profile,...next,widgets:normalizeWidgetPrefs(next.widgets),favoriteAppIds:next.favoriteAppIds||[]})}return send(res,405,{error:'Method not allowed'})}
function mergeSecretService(input,previous,secretKey){const enteredUrl=String(input?.url||'').trim(),enteredSecret=String(input?.[secretKey]||'').trim();return {url:enteredUrl?cleanUrl(enteredUrl):previous?.url||'',[secretKey]:enteredSecret||previous?.[secretKey]||''}}
function normalizeQuickActions(actions){return (Array.isArray(actions)?actions:[]).slice(0,12).map((action,index)=>({id:String(action.id||`action-${index}`),name:String(action.name||'Action').trim().slice(0,60),entityId:String(action.entityId||'').trim(),service:['toggle','turn_on','turn_off','lock','unlock','open_cover','close_cover'].includes(action.service)?action.service:'toggle'})).filter(action=>/^[a-z_]+\.[a-zA-Z0-9_]+$/.test(action.entityId))}
async function configureIntegrations(req,res){
  const identity=await authenticatedIdentity(req);if(!identity)return send(res,401,{error:'Keycloak authentication required'});
  try{
    const body=await readJson(req),prefs=userPreferences[identity.sub]||{},personal=prefs.integrations||{},haCredentials=mergeSecretService(body.homeAssistant,integrations.homeAssistant,'token'),vikunjaCredentials=mergeSecretService(body.vikunja,personal.vikunja||(identity.sub===integrationOwnerSub?integrations.vikunja:{}),'token'),immichCredentials=mergeSecretService(body.immich,personal.immich||{},'apiKey'),enteredCalendarEntity=String(body.homeAssistant?.calendarEntity||'').trim(),rawCalendarEntity=enteredCalendarEntity||integrations.homeAssistant.calendarEntity,calendarEntity=rawCalendarEntity&&!rawCalendarEntity.startsWith('calendar.')?`calendar.${rawCalendarEntity}`:rawCalendarEntity,whiskerEntity=String(body.homeAssistant?.whiskerEntity||'').trim()||integrations.homeAssistant.whiskerEntity,enteredChoreUrl=String(body.chores?.url||'').trim();
    vikunjaCredentials.token=vikunjaCredentials.token.replace(/^Bearer\s+/i,'').trim();
    userPreferences[identity.sub]={...prefs,integrations:{...personal,vikunja:vikunjaCredentials,immich:immichCredentials}};
    const canManageShared=true;
    const next={homeAssistant:{...haCredentials,calendarEntity,whiskerEntity,quickActions:normalizeQuickActions(body.homeAssistant?.quickActions??integrations.homeAssistant.quickActions)},plex:mergeSecretService(body.plex,integrations.plex,'token'),shelfLife:mergeSecretService(body.shelfLife,integrations.shelfLife,'apiKey'),vikunja:integrations.vikunja,chores:{url:enteredChoreUrl?cleanUrl(enteredChoreUrl):integrations.chores.url},calendar:{icsUrl:String(body.calendar?.icsUrl||'').trim()?cleanUrl(body.calendar.icsUrl):integrations.calendar.icsUrl},arrs:{}};for(const name of Object.keys(emptyIntegrations.arrs))next.arrs[name]=mergeSecretService(body.arrs?.[name],integrations.arrs[name],'apiKey');integrations=next;
    await persistSettings();return send(res,200,{ok:true,canManageShared});
  }catch(error){return send(res,400,{error:error.message||'Invalid integration settings'})}
}

const weatherDescriptions={0:'Clear sky',1:'Mainly clear',2:'Partly cloudy',3:'Overcast',45:'Foggy',48:'Rime fog',51:'Light drizzle',53:'Drizzle',55:'Heavy drizzle',61:'Light rain',63:'Rain',65:'Heavy rain',71:'Light snow',73:'Snow',75:'Heavy snow',80:'Rain showers',81:'Rain showers',82:'Heavy showers',95:'Thunderstorms',96:'Thunderstorms',99:'Severe thunderstorms'};
async function weather(res,url){
  const location=String(url.searchParams.get('location')||'').trim();if(!location)return send(res,400,{error:'Weather location is required'});
  try{
    const geoUrl=new URL('https://geocoding-api.open-meteo.com/v1/search');geoUrl.search=new URLSearchParams({name:location,count:'1',language:'en',format:'json'});
    const geo=await (await fetch(geoUrl,{signal:AbortSignal.timeout(8000)})).json(),place=geo.results?.[0];if(!place)return send(res,404,{error:'Location not found'});
    const forecastUrl=new URL('https://api.open-meteo.com/v1/forecast');forecastUrl.search=new URLSearchParams({latitude:String(place.latitude),longitude:String(place.longitude),current:'temperature_2m,relative_humidity_2m,weather_code,is_day',hourly:'temperature_2m,weather_code',temperature_unit:'fahrenheit',forecast_days:'2',timezone:'auto'});
    const data=await (await fetch(forecastUrl,{signal:AbortSignal.timeout(8000)})).json();
    const start=Math.max(0,data.hourly.time.findIndex(time=>time>=data.current.time));const hourly=data.hourly.time.slice(start,start+5).map((time,index)=>({time,temperature:Math.round(data.hourly.temperature_2m[start+index]),code:data.hourly.weather_code[start+index]}));
    return send(res,200,{location:[place.name,place.admin1].filter(Boolean).join(', '),temperature:Math.round(data.current.temperature_2m),humidity:Math.round(data.current.relative_humidity_2m),code:data.current.weather_code,condition:weatherDescriptions[data.current.weather_code]||'Current conditions',isDay:Boolean(data.current.is_day),hourly});
  }catch{return send(res,502,{error:'Weather service could not be reached'})}
}

function xmlDecode(value=''){return value.replaceAll('&amp;','&').replaceAll('&quot;','"').replaceAll('&apos;',"'").replaceAll('&lt;','<').replaceAll('&gt;','>')}
function xmlAttributes(text){const result={};for(const match of text.matchAll(/([\w:]+)="([^"]*)"/g))result[match[1]]=xmlDecode(match[2]);return result}
async function plexRecent(req,res){
  if(!await requireAuth(req,res))return;if(!integrations.plex.url||!integrations.plex.token)return send(res,503,{error:'Plex is not configured'});
  try{const response=await fetch(`${integrations.plex.url}/library/recentlyAdded?X-Plex-Token=${encodeURIComponent(integrations.plex.token)}`,{headers:{Accept:'application/xml'},signal:AbortSignal.timeout(10000)});if(!response.ok)return send(res,502,{error:`Plex returned ${response.status}`});const xml=await response.text(),items=[],seen=new Set();for(const match of xml.matchAll(/<Video\b([^>]*)>/g)){const item=xmlAttributes(match[1]),type=item.type||'';if(!['movie','episode'].includes(type)||!item.title)continue;const key=type==='episode'?(item.grandparentRatingKey||item.grandparentTitle):item.ratingKey;if(key&&seen.has(key))continue;if(key)seen.add(key);items.push({title:type==='episode'?(item.grandparentTitle||item.title):item.title,subtitle:type==='episode'?[item.parentTitle,item.title].filter(Boolean).join(' · '):'',year:item.year||'',type:type==='episode'?'TV':'Movie',addedAt:Number(item.addedAt||0),thumb:(type==='episode'?(item.grandparentThumb||item.thumb):item.thumb)?`/api/plex/image?path=${encodeURIComponent(type==='episode'?(item.grandparentThumb||item.thumb):item.thumb)}`:''});if(items.length===12)break}return send(res,200,{items})}catch{return send(res,502,{error:'Plex could not be reached'})}
}
async function plexImage(req,res,url){
  if(!await requireAuth(req,res))return;if(!integrations.plex.url||!integrations.plex.token)return send(res,503,{error:'Plex is not configured'});const path=String(url.searchParams.get('path')||'');if(!path.startsWith('/'))return send(res,400,{error:'Invalid image path'});
  try{const upstream=await fetch(`${integrations.plex.url}${path}${path.includes('?')?'&':'?'}X-Plex-Token=${encodeURIComponent(integrations.plex.token)}`,{signal:AbortSignal.timeout(10000)});const body=Buffer.from(await upstream.arrayBuffer());res.writeHead(upstream.status,{...securityHeaders(),'Content-Type':upstream.headers.get('content-type')||'image/jpeg','Cache-Control':'private, max-age=3600'});res.end(body)}catch{return send(res,502,{error:'Plex image unavailable'})}
}

function shelfLifeDinner(payload,date){const rows=Array.isArray(payload)?payload:Array.isArray(payload?.meals)?payload.meals:Array.isArray(payload?.items)?payload.items:[],direct=payload?.dinner||payload?.meal||null,item=direct||rows.find(row=>String(row.date||row.scheduled_date||row.meal_date||'').slice(0,10)===date&&(!row.type||/dinner/i.test(row.type)))||rows.find(row=>/dinner/i.test(String(row.type||row.meal_type||'')))||rows[0];if(!item)return null;const source=typeof item==='string'?{name:item}:item,title=source.name||source.title||source.recipe?.name||source.recipe?.title||source.meal?.name||source.meal?.title;return title?{title:String(title).slice(0,160),notes:String(source.notes||source.description||'').slice(0,300),image:String(source.image||source.image_url||source.recipe?.image||''),url:String(source.url||source.recipe?.url||'')} : null}
async function shelfLifeDinnerApi(req,res,url){if(!await requireAuth(req,res))return;const config=integrations.shelfLife;if(!config.url)return send(res,503,{error:'Shelf Life is not configured'});const date=/^\d{4}-\d{2}-\d{2}$/.test(String(url.searchParams.get('date')||''))?String(url.searchParams.get('date')):new Date().toISOString().slice(0,10),base=internalServiceUrl(config.url),headers={Accept:'application/json',...(config.apiKey?{'X-API-Key':config.apiKey,Authorization:`Bearer ${config.apiKey}`}:{})},targets=[`${base}/api/meals?date=${encodeURIComponent(date)}`,`${base}/api/meals/today`,`${base}/api/dinner?date=${encodeURIComponent(date)}`,`${base}/api/summary`];try{for(const target of targets){const response=await fetch(target,{headers,redirect:'manual',signal:AbortSignal.timeout(8000)});if(response.status===404)continue;if(!response.ok)throw new Error(`Shelf Life returned ${response.status}`);const type=response.headers.get('content-type')||'';if(!type.includes('json'))continue;const dinner=shelfLifeDinner(await response.json(),date);return send(res,200,{configured:true,date,dinner,url:config.url})}return send(res,200,{configured:true,date,dinner:null,url:config.url})}catch(error){return send(res,502,{error:error.message||'Shelf Life could not be reached'})}}

function parseIcsDate(value){const text=String(value||'').replace(/^.*:/,'');const match=text.match(/^(\d{4})(\d{2})(\d{2})(?:T(\d{2})(\d{2})(\d{2}))?(Z)?$/);if(!match)return null;const parts=match.slice(1,7).map(Number);return match[7]?new Date(Date.UTC(parts[0],parts[1]-1,parts[2],parts[3]||0,parts[4]||0,parts[5]||0)):new Date(parts[0],parts[1]-1,parts[2],parts[3]||0,parts[4]||0,parts[5]||0)}
function parseCalendar(text){const unfolded=text.replace(/\r?\n[ \t]/g,''),now=Date.now()-86400000,events=[];for(const block of unfolded.split('BEGIN:VEVENT').slice(1)){const body=block.split('END:VEVENT')[0],lines=body.split(/\r?\n/),summary=lines.find(line=>line.startsWith('SUMMARY'))?.replace(/^SUMMARY[^:]*:/,'').replace(/\\,/g,',').replace(/\\n/g,' ')||'Untitled event',start=parseIcsDate(lines.find(line=>line.startsWith('DTSTART'))),end=parseIcsDate(lines.find(line=>line.startsWith('DTEND')))||start;if(start&&end?.getTime()>=now)events.push({summary,start:start.toISOString(),end:end.toISOString(),allDay:!lines.find(line=>line.startsWith('DTSTART'))?.includes('T')})}return events.sort((a,b)=>a.start.localeCompare(b.start)).slice(0,20)}
async function calendarEvents(req,res){if(!await requireAuth(req,res))return;if(!integrations.calendar.icsUrl)return send(res,503,{error:'Calendar is not configured'});try{const response=await fetch(integrations.calendar.icsUrl,{signal:AbortSignal.timeout(10000)});if(!response.ok)return send(res,502,{error:`Calendar returned ${response.status}`});return send(res,200,{events:parseCalendar(await response.text())})}catch{return send(res,502,{error:'Calendar could not be reached'})}}

async function testIntegration(req,res,url){
  const identity=await authenticatedIdentity(req);if(!identity)return send(res,401,{error:'Keycloak authentication required'});const service=String(url.searchParams.get('service')||'');
  if(service==='immich'){try{const config=personalIntegration(identity,'immich');if(!config.url||!config.apiKey)throw new Error('Immich URL or API key is missing for this user');await immichAssets(config);return send(res,200,{ok:true})}catch(error){return send(res,502,{error:error.message||'Immich connection failed'})}}
  if(service==='vikunja'){
    let target='not resolved';
    try{
      const config=personalIntegration(identity,'vikunja');
      if(!config.url||!config.token)throw new Error('Vikunja URL or API token is missing for this user');
      target=`${vikunjaApiBase(config.url)}/user`;
      console.log(`Vikunja test: requesting ${target}`);
      const response=await fetch(target,{headers:{Authorization:`Bearer ${config.token.replace(/^Bearer\s+/i,'').trim()}`,Accept:'application/json'},redirect:'manual',signal:AbortSignal.timeout(8000)});
      if(!response.ok){const error=response.status===401?'Vikunja rejected this user’s API token (401)':`Vikunja returned HTTP ${response.status}`;console.error(`Vikunja test failed: ${error}`);return send(res,200,{ok:false,error,target})}
      console.log(`Vikunja test connected: ${target}`);
      return send(res,200,{ok:true,target});
    }catch(error){const reason=error?.cause?.code||error.message||'Vikunja connection failed';console.error(`Vikunja test failed for ${target}: ${reason}`);return send(res,200,{ok:false,error:`Could not reach Vikunja: ${reason}`,target})}
  }
  if(service==='shelfLife')return shelfLifeDinnerApi(req,res,new URL(req.url,'http://haven'));
  try{let target,headers={};if(service==='homeAssistant'){const config=integrations.homeAssistant;if(!config.url||!config.token)throw new Error('Home Assistant is not configured');target=`${config.url}/api/`;headers.Authorization=`Bearer ${config.token}`}else if(service==='plex'){if(!integrations.plex.url||!integrations.plex.token)throw new Error('Plex is not configured');target=`${integrations.plex.url}/identity`;headers['X-Plex-Token']=integrations.plex.token}else if(service==='vikunja'){if(!integrations.vikunja.url||!integrations.vikunja.token)throw new Error('Vikunja URL or API token is missing');target=`${vikunjaApiBase(integrations.vikunja.url)}/user`;headers={Authorization:`Bearer ${integrations.vikunja.token.replace(/^Bearer\s+/i,'').trim()}`,Accept:'application/json'}}else if(service==='homeAssistantCalendar'){const config=integrations.homeAssistant,entity=config.calendarEntity;if(!config.url||!config.token||!entity)throw new Error('Home Assistant calendar is not configured');const start=new Date(),end=new Date(start.getTime()+86400000),query=new URLSearchParams({start:start.toISOString(),end:end.toISOString()});target=`${config.url}/api/calendars/${encodeURIComponent(entity)}?${query}`;headers.Authorization=`Bearer ${config.token}`}else if(service==='chores'){if(!integrations.chores.url)throw new Error('Chore app is not configured');target=`${integrations.chores.url}/api/summary`}else if(service==='calendar'){if(!integrations.calendar.icsUrl)throw new Error('Calendar is not configured');target=integrations.calendar.icsUrl}else if(integrations.arrs[service]){const config=integrations.arrs[service];if(!config.url||!config.apiKey)throw new Error(`${service} is not configured`);target=`${config.url}/api/v3/system/status`;headers['X-Api-Key']=config.apiKey}else throw new Error('Unknown integration');const response=await fetch(target,{headers,redirect:service==='vikunja'?'manual':'follow',signal:AbortSignal.timeout(8000)});if(service==='vikunja'&&!response.ok){const detail=response.status===401?'Vikunja rejected the API token (401). Paste a current API token—not a password.':response.status>=300&&response.status<400?'Vikunja redirected the API request. Check the saved Vikunja URL.':`Vikunja API returned ${response.status}.`;return send(res,502,{ok:false,status:response.status,error:detail})}return send(res,response.ok?200:502,{ok:response.ok,status:response.status,...(!response.ok?{error:`${service} returned ${response.status}`}:{})})}catch(error){const reason=error?.cause?.code||error.message||'Connection failed';return send(res,502,{error:`Could not reach ${service}: ${reason}`})}
}

async function haFetch(path,options={}){const config=integrations.homeAssistant;if(!config.url||!config.token)throw new Error('Home Assistant is not configured');return fetch(`${config.url}${path}`,{...options,headers:{Authorization:`Bearer ${config.token}`,'Content-Type':'application/json',...(options.headers||{})},signal:AbortSignal.timeout(10000)})}
const entityView=state=>({entityId:state.entity_id,state:state.state,name:state.attributes?.friendly_name||state.entity_id.split('.')[1].replaceAll('_',' '),domain:state.entity_id.split('.')[0],unit:state.attributes?.unit_of_measurement||'',deviceClass:state.attributes?.device_class||''});
async function homeAssistantDashboard(req,res){if(!await requireAuth(req,res))return;try{const response=await haFetch('/api/states');if(!response.ok)return send(res,502,{error:`Home Assistant returned ${response.status}`});const states=await response.json(),entities=states.filter(item=>['light','switch','lock','cover','scene','script','automation'].includes(item.entity_id.split('.')[0])).map(entityView),temperature=states.find(item=>item.attributes?.device_class==='temperature'&&Number.isFinite(Number(item.state))),humidity=states.find(item=>item.attributes?.device_class==='humidity'&&Number.isFinite(Number(item.state))),lights=states.filter(item=>item.entity_id.startsWith('light.')),locks=states.filter(item=>item.entity_id.startsWith('lock.'));return send(res,200,{summary:{temperature:temperature?`${Math.round(Number(temperature.state))}${temperature.attributes?.unit_of_measurement||'°'}`:'—',humidity:humidity?`${Math.round(Number(humidity.state))}${humidity.attributes?.unit_of_measurement||'%'}`:'—',lightsOn:lights.filter(item=>item.state==='on').length,lightsTotal:lights.length,locksLocked:locks.filter(item=>item.state==='locked').length,locksTotal:locks.length},entities,quickActions:integrations.homeAssistant.quickActions||[]})}catch(error){return send(res,502,{error:error.message||'Home Assistant could not be reached'})}}
async function homeAssistantAction(req,res){if(!await requireAuth(req,res))return;try{const body=await readJson(req),entityId=String(body.entityId||''),domain=entityId.split('.')[0];if(!/^[a-z_]+\.[a-zA-Z0-9_]+$/.test(entityId))return send(res,400,{error:'Invalid entity ID'});const allowed={light:['toggle','turn_on','turn_off'],switch:['toggle','turn_on','turn_off'],lock:['lock','unlock'],cover:['open_cover','close_cover'],scene:['turn_on'],script:['turn_on'],automation:['trigger']},requested=String(body.service||'toggle'),service=domain==='scene'||domain==='script'?'turn_on':domain==='automation'?'trigger':requested;if(!allowed[domain]?.includes(service))return send(res,400,{error:'That action is not allowed'});const upstream=await haFetch(`/api/services/${domain}/${service}`,{method:'POST',body:JSON.stringify({entity_id:entityId})});if(!upstream.ok)return send(res,502,{error:`Home Assistant returned ${upstream.status}`});return send(res,200,{ok:true})}catch(error){return send(res,502,{error:error.message||'Home Assistant action failed'})}}
async function homeAssistantWhisker(req,res){if(!await requireAuth(req,res))return;try{let entityId=integrations.homeAssistant.whiskerEntity,state;if(entityId){const response=await haFetch(`/api/states/${encodeURIComponent(entityId)}`);if(!response.ok)return send(res,502,{error:`Home Assistant returned ${response.status}`});state=await response.json()}else{const response=await haFetch('/api/states');if(!response.ok)return send(res,502,{error:`Home Assistant returned ${response.status}`});state=(await response.json()).find(item=>/(whisker|litter[ _-]?(robot|box)|litter-robot)/i.test(`${item.entity_id} ${item.attributes?.friendly_name||''}`));if(!state)return send(res,503,{error:'Choose a Whisker entity in Integrations'});entityId=state.entity_id}const details=Object.entries(state.attributes||{}).filter(([key,value])=>['status','waste_drawer','waste_drawer_level','litter_level','clean_cycle_wait_time_minutes'].includes(key)&&['string','number','boolean'].includes(typeof value)).map(([key,value])=>({label:key.replaceAll('_',' '),value:String(value)}));return send(res,200,{entityId,name:state.attributes?.friendly_name||'Whisker',state:state.state,unit:state.attributes?.unit_of_measurement||'',updated:state.last_updated||'',details})}catch(error){return send(res,502,{error:error.message||'Whisker status could not be reached'})}}
async function homeAssistantCalendar(req,res){if(!await requireAuth(req,res))return;const entity=integrations.homeAssistant.calendarEntity;if(!entity)return send(res,503,{error:'Home Assistant calendar entity is not configured'});try{const requestUrl=new URL(req.url,'http://haven'),requestedStart=new Date(requestUrl.searchParams.get('start')||Date.now()),requestedEnd=new Date(requestUrl.searchParams.get('end')||requestedStart.getTime()+31*86400000),start=Number.isNaN(requestedStart.getTime())?new Date():requestedStart,maxEnd=new Date(start.getTime()+93*86400000),end=Number.isNaN(requestedEnd.getTime())||requestedEnd<=start||requestedEnd>maxEnd?maxEnd:requestedEnd,query=new URLSearchParams({start:start.toISOString(),end:end.toISOString()}),response=await haFetch(`/api/calendars/${encodeURIComponent(entity)}?${query}`);if(!response.ok)return send(res,502,{error:`Home Assistant returned ${response.status}`});const events=[];for(const event of await response.json()){const startValue=event.start?.dateTime||event.start?.date,endValue=event.end?.dateTime||event.end?.date,startDate=new Date(startValue),endDate=new Date(endValue||startValue);if(!startValue||Number.isNaN(startDate.getTime()))continue;events.push({summary:event.summary||'Untitled event',start:startDate.toISOString(),end:Number.isNaN(endDate.getTime())?startDate.toISOString():endDate.toISOString(),allDay:Boolean(event.start?.date&&!event.start?.dateTime),date:event.start?.date||'',endDate:event.end?.date||'',description:event.description||''})}return send(res,200,{events})}catch(error){return send(res,502,{error:error.message||'Home Assistant calendar could not be reached'})}}
function internalServiceUrl(value){
  const parsed=new URL(String(value));
  if(hostLanIp&&parsed.hostname===hostLanIp)parsed.hostname='host.docker.internal';
  return parsed.toString().replace(/\/$/,'');
}
const vikunjaApiBase=url=>`${internalServiceUrl(url).replace(/\/api\/v1\/?$/,'')}/api/v1`;
function personalIntegration(identity,name){const saved=userPreferences[identity.sub]?.integrations?.[name];if(saved)return saved;if(name==='vikunja'&&identity.sub===integrationOwnerSub)return integrations.vikunja;return {}}
async function vikunjaJson(response,label){const type=response.headers.get('content-type')||'',text=await response.text();if(!response.ok)throw new Error(`${label} returned ${response.status}`);if(!type.includes('json')||/^\s*</.test(text))throw new Error(`${label} returned a web page instead of API JSON. Check the Vikunja URL and reverse proxy.`);try{return JSON.parse(text)}catch{throw new Error(`${label} returned invalid JSON`)}}
async function vikunjaOpenTasks(config){if(!config.url||!config.token)throw new Error('Vikunja is not configured for this user');const headers={Authorization:`Bearer ${config.token}`,Accept:'application/json'},base=vikunjaApiBase(config.url),query=new URLSearchParams({filter:'done = false',filter_include_nulls:'false',sort_by:'due_date',order_by:'asc',per_page:'100',expand:'buckets'});let response=await fetch(`${base}/tasks?${query}`,{headers,redirect:'manual',signal:AbortSignal.timeout(10000)});if(response.status===404)response=await fetch(`${base}/tasks/all?${query}`,{headers,redirect:'manual',signal:AbortSignal.timeout(10000)});return vikunjaJson(response,'Vikunja tasks')}
async function vikunjaProjectContext(config,projectId){
  const headers={Authorization:`Bearer ${config.token}`,Accept:'application/json'},base=vikunjaApiBase(config.url),todoIds=new Set(),workingIds=new Set();
  try{
    const [projectResponse,viewsResponse]=await Promise.all([fetch(`${base}/projects/${projectId}`,{headers,signal:AbortSignal.timeout(8000)}),fetch(`${base}/projects/${projectId}/views`,{headers,signal:AbortSignal.timeout(8000)})]),project=await vikunjaJson(projectResponse,'Vikunja project'),views=await vikunjaJson(viewsResponse,'Vikunja views'),kanbanViews=(Array.isArray(views)?views:[]).filter(view=>view.view_kind==='kanban');
    await Promise.all(kanbanViews.map(async view=>{const [bucketsResponse,tasksResponse]=await Promise.all([fetch(`${base}/projects/${projectId}/views/${view.id}/buckets`,{headers,signal:AbortSignal.timeout(8000)}),fetch(`${base}/projects/${projectId}/views/${view.id}/tasks?per_page=200&expand=buckets`,{headers,signal:AbortSignal.timeout(8000)})]),buckets=await vikunjaJson(bucketsResponse,'Vikunja buckets'),viewTasks=await vikunjaJson(tasksResponse,'Vikunja board tasks'),todo=(Array.isArray(buckets)?buckets:[]).find(bucket=>/^to[\s-]*do$/i.test(String(bucket.title||'').trim())),working=(Array.isArray(buckets)?buckets:[]).find(bucket=>/^working[\s-]*on$/i.test(String(bucket.title||'').trim())),inBucket=(task,bucket)=>Boolean(bucket)&&(String(task.bucket_id)===String(bucket.id)||(task.buckets||[]).some(item=>String(item.id)===String(bucket.id)));for(const task of Array.isArray(viewTasks)?viewTasks:[]){if(inBucket(task,todo))todoIds.add(String(task.id));if(inBucket(task,working))workingIds.add(String(task.id))}}));
    return {title:project.title||`Project ${projectId}`,todoIds,workingIds,kanbanViews:kanbanViews.length};
  }catch(error){console.warn(`Vikunja project ${projectId} context unavailable: ${error.message}`);return {title:`Project ${projectId}`,todoIds,workingIds,kanbanViews:0}}
}
async function vikunjaTokenOwner(config){const headers={Authorization:`Bearer ${config.token}`,Accept:'application/json'},response=await fetch(`${vikunjaApiBase(config.url)}/user`,{headers,redirect:'manual',signal:AbortSignal.timeout(8000)}),user=await vikunjaJson(response,'Vikunja user');return {id:Number(user.id),name:user.name||user.username||user.email||`User ${user.id}`,username:user.username||'',email:user.email||''}}
function vikunjaPeople(tasks){const people=new Map();for(const task of tasks)for(const person of task.assignees||[])if(person?.id!=null)people.set(String(person.id),{id:Number(person.id),name:person.name||person.username||person.email||`User ${person.id}`,username:person.username||'',email:person.email||''});return [...people.values()]}
function suggestedVikunjaUser(identity,people){const terms=[identity.email,identity.preferred_username,identity.name].filter(Boolean).map(value=>String(value).toLowerCase());return people.find(person=>terms.some(term=>[person.email,person.username,person.name].some(value=>String(value||'').toLowerCase()===term)))||null}
async function vikunjaUsers(req,res){const identity=await authenticatedIdentity(req);if(!identity)return send(res,401,{error:'Keycloak authentication required'});const config=personalIntegration(identity,'vikunja');try{const [tasks,tokenOwner]=await Promise.all([vikunjaOpenTasks(config),vikunjaTokenOwner(config)]),users=vikunjaPeople(tasks);if(!users.some(user=>user.id===tokenOwner.id))users.unshift(tokenOwner);const prefs=userPreferences[identity.sub]||{},suggested=prefs.vikunjaRejected?null:suggestedVikunjaUser(identity,users);return send(res,200,{users,tokenOwner,suggested,selectedUserId:prefs.vikunjaUserId??null})}catch(error){return send(res,502,{error:error.message||'Vikunja users could not be loaded'})}}
async function vikunjaTasks(req,res){const identity=await authenticatedIdentity(req);if(!identity)return send(res,401,{error:'Keycloak authentication required'});const config=personalIntegration(identity,'vikunja');if(!config.url||!config.token)return send(res,503,{error:'Vikunja is not configured for this user'});try{const [allTasks,tokenOwner]=await Promise.all([vikunjaOpenTasks(config),vikunjaTokenOwner(config)]),people=vikunjaPeople(allTasks),prefs=userPreferences[identity.sub]||{},suggested=prefs.vikunjaRejected?null:suggestedVikunjaUser(identity,people),userId=prefs.vikunjaUserId??suggested?.id??tokenOwner.id,assigned=allTasks.filter(task=>(task.assignees||[]).some(assignee=>String(assignee.id)===String(userId))),projectIds=[...new Set(assigned.map(task=>Number(task.project_id)).filter(Boolean))],contexts=new Map(await Promise.all(projectIds.map(async id=>[id,await vikunjaProjectContext(config,id)]))),publicBase=String(config.url).replace(/\/api\/v1\/?$/,'').replace(/\/$/,''),now=Date.now(),bucketColumn=task=>{const titles=(task.buckets||[]).map(bucket=>String(bucket.title||'').trim());if(titles.some(title=>/^to[\s-]*do$/i.test(title)))return'todo';if(titles.some(title=>/^working[\s-]*on$/i.test(title)))return'working';const context=contexts.get(Number(task.project_id)),id=String(task.id);return context?.todoIds.has(id)?'todo':context?.workingIds.has(id)?'working':null},tasks=assigned.map(task=>{const context=contexts.get(Number(task.project_id)),column=bucketColumn(task);if(!column)return null;const due=task.due_date||'',dueTime=new Date(due).getTime();return {id:task.id,title:task.title||'Untitled task',column,dueDate:due,overdue:Boolean(due&&dueTime>0&&dueTime<now),priority:Number(task.priority||0),projectId:task.project_id||0,projectName:context?.title||'Vikunja',url:`${publicBase}/tasks/${encodeURIComponent(task.id)}`}}).filter(Boolean).sort((a,b)=>(a.dueDate||'9999').localeCompare(b.dueDate||'9999')).slice(0,24);return send(res,200,{url:publicBase,tasks,diagnostics:{openTasks:allTasks.length,assignedTasks:assigned.length,projects:projectIds.length,kanbanViews:[...contexts.values()].reduce((sum,item)=>sum+item.kanbanViews,0),matchedTasks:tasks.length},mapped:Boolean(prefs.vikunjaUserId),usingTokenOwner:userId===tokenOwner.id,suggested:!prefs.vikunjaUserId?suggested:null})}catch(error){return send(res,502,{error:error.message||'Vikunja could not be reached'})}}
const immichApiBase=url=>`${internalServiceUrl(url).replace(/\/api\/?$/,'')}/api`;
async function immichAssets(config){const headers={'x-api-key':config.apiKey,Accept:'application/json'},base=immichApiBase(config.url);let response=await fetch(`${base}/search/random`,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({size:8,type:'IMAGE'}),signal:AbortSignal.timeout(10000)});if(response.status===404||response.status===405)response=await fetch(`${base}/assets/random?count=8`,{headers,signal:AbortSignal.timeout(10000)});if(!response.ok)throw new Error(response.status===401?'Immich rejected this API key (401)':`Immich returned ${response.status}`);const data=await response.json();return Array.isArray(data)?data:Array.isArray(data.assets)?data.assets:[]}
async function immichPhotos(req,res){const identity=await authenticatedIdentity(req);if(!identity)return send(res,401,{error:'Keycloak authentication required'});const config=personalIntegration(identity,'immich');if(!config.url||!config.apiKey)return send(res,503,{error:'Immich is not configured for this user'});try{const assets=await immichAssets(config);return send(res,200,{url:config.url,photos:assets.slice(0,8).map(asset=>({id:String(asset.id),title:asset.originalFileName||'Photo',date:asset.localDateTime||asset.fileCreatedAt||''}))})}catch(error){return send(res,502,{error:error.message||'Immich could not be reached'})}}
async function immichImage(req,res,url){const identity=await authenticatedIdentity(req);if(!identity)return send(res,401,{error:'Keycloak authentication required'});const config=personalIntegration(identity,'immich'),id=String(url.searchParams.get('id')||'');if(!config.url||!config.apiKey)return send(res,503,{error:'Immich is not configured for this user'});if(!/^[a-zA-Z0-9-]+$/.test(id))return send(res,400,{error:'Invalid asset ID'});try{const upstream=await fetch(`${immichApiBase(config.url)}/assets/${id}/thumbnail?size=preview`,{headers:{'x-api-key':config.apiKey,Accept:'image/*'},signal:AbortSignal.timeout(10000)});if(!upstream.ok)return send(res,502,{error:`Immich image returned ${upstream.status}`});const body=Buffer.from(await upstream.arrayBuffer());res.writeHead(200,{...securityHeaders(),'Content-Type':upstream.headers.get('content-type')||'image/jpeg','Cache-Control':'private, max-age=900'});return res.end(body)}catch(error){return send(res,502,{error:error.message||'Immich image unavailable'})}}
const pendingList=(payload,key)=>Array.isArray(payload)?payload:Array.isArray(payload?.[key])?payload[key]:Array.isArray(payload?.[`pending_${key}`])?payload[`pending_${key}`]:Array.isArray(payload?.pending)?payload.pending:Array.isArray(payload?.items)?payload.items:Array.isArray(payload?.data)?payload.data:[];
async function chorePayload(response,label){const type=response.headers.get('content-type')||'',text=await response.text();if(!response.ok)throw new Error(`${label} returned HTTP ${response.status}`);if(!type.includes('json')||/^\s*</.test(text))throw new Error(`${label} returned a web page. Save only the chore app address and port, without /admin/login.`);try{return JSON.parse(text)}catch{throw new Error(`${label} returned invalid JSON`)}}
async function choreRequests(req,res){if(!await requireAuth(req,res))return;const config=integrations.chores;if(!config.url)return send(res,200,{configured:false,items:[]});try{const publicUrl=new URL(config.url),base=internalServiceUrl(publicUrl.origin),[choresResponse,rewardsResponse]=await Promise.all([fetch(`${base}/api/chores/pending`,{headers:{Accept:'application/json'},redirect:'manual',signal:AbortSignal.timeout(8000)}),fetch(`${base}/api/rewards/pending`,{headers:{Accept:'application/json'},redirect:'manual',signal:AbortSignal.timeout(8000)})]),[choresData,rewardsData]=await Promise.all([chorePayload(choresResponse,'Pending chores'),chorePayload(rewardsResponse,'Pending rewards')]),mapItem=(item,kind)=>{const review=item.review_url||item.url||'/admin/';return {kind,title:(kind==='Chore'?item.chore_name||item.chore?.name:item.reward_name||item.reward?.name)||item.name||item.title||`${kind} request`,person:item.child_name||item.child?.name||item.user_name||item.user?.name||'',detail:item.notes||item.description||'',submittedAt:item.submitted_at||item.requested_at||item.created_at||item.created||'',reviewUrl:new URL(review,publicUrl.origin).href}},chores=pendingList(choresData,'chores').map(item=>mapItem(item,'Chore')),rewards=pendingList(rewardsData,'rewards').map(item=>mapItem(item,'Reward'));return send(res,200,{configured:true,url:publicUrl.origin,items:[...chores,...rewards].sort((a,b)=>String(b.submittedAt).localeCompare(String(a.submittedAt))).slice(0,10)})}catch(error){return send(res,502,{error:error.message||'Chore app could not be reached'})}}
async function appIcon(req,res,url){
  if(!await requireAuth(req,res))return;
  try{
    const target=internalServiceUrl(cleanUrl(url.searchParams.get('url'))),base=new URL(target),explicit=String(url.searchParams.get('icon')||'').trim(),page=await fetch(base,{headers:{Accept:'text/html'},redirect:'follow',signal:AbortSignal.timeout(6000)}),pageUrl=page.url||base.href,html=(page.headers.get('content-type')||'').includes('text/html')?await page.text():'';
    const discovered=[];
    for(const match of html.matchAll(/<link\b[^>]*>/gi)){
      const tag=match[0],rel=tag.match(/rel=["']([^"']+)/i)?.[1]||'',href=tag.match(/href=["']([^"']+)/i)?.[1]||'';
      if(href&&/(?:^|\s)(?:icon|shortcut icon|apple-touch-icon)(?:\s|$)/i.test(rel))discovered.push(new URL(href,pageUrl).href);
    }
    const candidates=[...(explicit?[internalServiceUrl(cleanUrl(explicit))]:[]),...discovered,new URL('favicon.ico',pageUrl).href,new URL('/favicon.ico',base).href,new URL('/favicon.png',base).href,new URL('/favicon.svg',base).href,new URL('/apple-touch-icon.png',base).href,new URL('/android-chrome-192x192.png',base).href,new URL('/web-app-manifest-192x192.png',base).href,new URL('/static/favicon.png',base).href,new URL('/static/icons/favicon-192x192.png',base).href,new URL('/images/icons/favicon-32x32.png',base).href,new URL('/logo.png',base).href];
    for(const candidate of [...new Set(candidates)]){
      try{const icon=await fetch(candidate,{headers:{Accept:'image/avif,image/webp,image/svg+xml,image/*,*/*;q=0.8'},redirect:'follow',signal:AbortSignal.timeout(6000)});if(!icon.ok)continue;const type=(icon.headers.get('content-type')||'').toLowerCase(),body=Buffer.from(await icon.arrayBuffer());if(type.includes('text/html')||/^\s*<!doctype|^\s*<html/i.test(body.subarray(0,100).toString('utf8')))continue;if(!type.startsWith('image/')&&!/\.(?:ico|png|svg)(?:$|\?)/i.test(candidate))continue;if(!body.length||body.length>2097152)continue;res.writeHead(200,{...securityHeaders(),'Content-Type':type||'image/x-icon','Cache-Control':'private, max-age=86400'});return res.end(body)}catch{}
    }
    const label=String(url.searchParams.get('name')||base.hostname||'?').trim().slice(0,1).toUpperCase().replace(/[<>&"']/g,'')||'?';
    const fallback=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><rect width="128" height="128" rx="28" fill="#52645c"/><text x="64" y="82" text-anchor="middle" font-family="Arial,sans-serif" font-size="64" font-weight="700" fill="white">${label}</text></svg>`;
    res.writeHead(200,{...securityHeaders(),'Content-Type':'image/svg+xml','Cache-Control':'private, max-age=3600'});return res.end(fallback);
  }catch{res.writeHead(204,{...securityHeaders(),'Cache-Control':'private, max-age=60'});return res.end()}
}

async function homeAssistant(req,res,url){if(!await requireAuth(req,res))return;const config=integrations.homeAssistant;if(!config.url||!config.token)return send(res,503,{error:'Home Assistant is not configured on the server'});const suffix=url.pathname.replace('/api/home-assistant','')||'/api/';if(!suffix.startsWith('/api/'))return send(res,400,{error:'Only Home Assistant API paths are allowed'});try{const upstream=await fetch(`${config.url}${suffix}${url.search}`,{method:req.method,headers:{Authorization:`Bearer ${config.token}`,'Content-Type':req.headers['content-type']||'application/json'},signal:AbortSignal.timeout(10000)});const body=Buffer.from(await upstream.arrayBuffer());res.writeHead(upstream.status,{...securityHeaders(),'Content-Type':upstream.headers.get('content-type')||'application/json','Cache-Control':'no-store'});res.end(body)}catch{return send(res,502,{error:'Home Assistant could not be reached'})}}

function integrationStatus(identity=null){const includePrivate=Boolean(identity),canManageShared=Boolean(identity&&(!integrationOwnerSub||identity.sub===integrationOwnerSub)),arrs={};for(const [name,config] of Object.entries(integrations.arrs))arrs[name]={configured:Boolean(config.url&&config.apiKey),...(includePrivate?{url:config.url}:{})};const vikunja=identity?personalIntegration(identity,'vikunja'):{},immich=identity?personalIntegration(identity,'immich'):{};return {version,canManageShared,homeAssistant:{configured:Boolean(integrations.homeAssistant.url&&integrations.homeAssistant.token),...(includePrivate?{url:integrations.homeAssistant.url,calendarEntity:integrations.homeAssistant.calendarEntity||'',whiskerEntity:integrations.homeAssistant.whiskerEntity||'',quickActions:integrations.homeAssistant.quickActions||[]}:{})},keycloak:{configured:Boolean(runtimeAuth.enabled&&runtimeAuth.url&&runtimeAuth.realm),url:runtimeAuth.url,realm:runtimeAuth.realm,clientId:runtimeAuth.clientId,enabled:runtimeAuth.enabled,bypassed:authBypass},plex:{configured:Boolean(integrations.plex.url&&integrations.plex.token),...(includePrivate?{url:integrations.plex.url}:{})},shelfLife:{configured:Boolean(integrations.shelfLife.url),...(includePrivate?{url:integrations.shelfLife.url}:{})},vikunja:{configured:Boolean(vikunja.url&&vikunja.token),...(includePrivate?{url:vikunja.url||''}:{})},immich:{configured:Boolean(immich.url&&immich.apiKey),...(includePrivate?{url:immich.url||''}:{})},chores:{configured:Boolean(integrations.chores.url),...(includePrivate?{url:integrations.chores.url}:{})},calendar:{configured:Boolean(integrations.calendar.icsUrl)},arrs,setup:{available:Boolean(setupToken)}}}
async function integrationsStatusApi(req,res){return send(res,200,integrationStatus(await authenticatedIdentity(req)))}
async function staticFile(req,res,url){const requestPath=url.pathname==='/'?'/index.html':url.pathname,safePath=normalize(requestPath).replace(/^(\.\.[/\\])+/,'');let filePath=join(publicDir,safePath);if(!filePath.startsWith(publicDir))return send(res,403,'Forbidden','text/plain');try{if(!(await stat(filePath)).isFile())throw new Error()}catch{filePath=join(publicDir,'index.html')}try{const body=await readFile(filePath),cache=filePath.endsWith('config.js')?'no-store':filePath.endsWith('app.js')||filePath.endsWith('service-worker.js')?'no-cache':'public, max-age=3600';res.writeHead(200,{...securityHeaders(),'Content-Type':mime[extname(filePath)]||'application/octet-stream','Cache-Control':cache});res.end(body)}catch{return send(res,404,'Not found','text/plain')}}

async function routeRequest(req,res){const url=new URL(req.url,'http://haven');if(url.pathname==='/health')return send(res,200,'healthy\n','text/plain');if(url.pathname==='/api/me')return meApi(req,res);if(url.pathname==='/api/applications')return applicationsApi(req,res);if(url.pathname==='/api/dashboard')return dashboardApi(req,res);if(url.pathname==='/api/integrations')return send(res,200,integrationStatus(await authenticated(req)));if(url.pathname==='/api/setup/keycloak'&&req.method==='POST')return configureKeycloak(req,res);if(url.pathname==='/api/setup/integrations'&&req.method==='POST')return configureIntegrations(req,res);if(url.pathname==='/api/weather')return weather(res,url);if(url.pathname==='/api/plex/recent')return plexRecent(req,res);if(url.pathname==='/api/plex/image')return plexImage(req,res,url);if(url.pathname==='/api/calendar/events')return calendarEvents(req,res);if(url.pathname==='/api/integrations/test')return testIntegration(req,res,url);if(url.pathname==='/api/vikunja/test'&&req.method==='POST'){url.searchParams.set('service','vikunja');return testIntegration(req,res,url)}if(url.pathname==='/api/home-assistant/dashboard')return homeAssistantDashboard(req,res);if(url.pathname==='/api/home-assistant/action'&&req.method==='POST')return homeAssistantAction(req,res);if(url.pathname==='/api/home-assistant/calendar')return homeAssistantCalendar(req,res);if(url.pathname==='/api/vikunja/users')return vikunjaUsers(req,res);if(url.pathname==='/api/vikunja/tasks')return vikunjaTasks(req,res);if(url.pathname==='/api/immich/photos')return immichPhotos(req,res);if(url.pathname==='/api/immich/image')return immichImage(req,res,url);if(url.pathname==='/api/chores/pending')return choreRequests(req,res);if(url.pathname==='/api/app-icon')return appIcon(req,res,url);if(url.pathname.startsWith('/api/home-assistant'))return homeAssistant(req,res,url);if(url.pathname.startsWith('/api/'))return send(res,404,{error:'API endpoint not found',path:url.pathname});return staticFile(req,res,url)}
createServer((req,res)=>{const requestUrl=new URL(req.url,'http://haven'),pathname=requestUrl.pathname,handler=pathname==='/api/backup'?backupApi(req,res):pathname==='/api/daily-tasks'?dailyTasksApi(req,res,requestUrl):pathname==='/api/shelf-life/dinner'?shelfLifeDinnerApi(req,res,requestUrl):pathname==='/api/home-assistant/whisker'?homeAssistantWhisker(req,res):routeRequest(req,res);return handler.catch(error=>{console.error('Unhandled request error',req.method,req.url,error);if(!res.headersSent)return send(res,500,{error:error.message||'Unexpected Haven server error'});res.end()})}).listen(port,'0.0.0.0',()=>console.log(`Haven listening on ${port}`));
