import { createServer } from 'node:http';
import { readFile, stat, writeFile, mkdir } from 'node:fs/promises';
import { extname, join, normalize } from 'node:path';

const port = Number(process.env.PORT || 3000);
const version = process.env.HAVEN_VERSION || '0.5.19';
const publicDir = process.env.PUBLIC_DIR || '/app/public';
const dataDir = process.env.DATA_DIR || '/app/data';
const settingsFile = join(dataDir,'settings.json');
const setupToken = process.env.HAVEN_SETUP_TOKEN || '';
const authBypass = String(process.env.HAVEN_AUTH_BYPASS).toLowerCase()==='true';
const baseAuth = {enabled:String(process.env.KEYCLOAK_ENABLED).toLowerCase()==='true',url:(process.env.KEYCLOAK_URL||'').replace(/\/$/,''),realm:process.env.KEYCLOAK_REALM||'',clientId:process.env.KEYCLOAK_CLIENT_ID||'haven'};
const emptyIntegrations = {homeAssistant:{url:(process.env.HOME_ASSISTANT_URL||'').replace(/\/$/,''),token:process.env.HOME_ASSISTANT_TOKEN||'',calendarEntity:'',quickActions:[]},plex:{url:'',token:''},vikunja:{url:'',token:''},chores:{url:''},calendar:{icsUrl:''},arrs:{sonarr:{url:'',apiKey:''},radarr:{url:'',apiKey:''},lidarr:{url:'',apiKey:''},readarr:{url:'',apiKey:''}}};
let storedSettings = {};
await mkdir(dataDir,{recursive:true});
try{storedSettings=JSON.parse(await readFile(settingsFile,'utf8'))}catch{}
let runtimeAuth = {...baseAuth,...(storedSettings.auth||{})};
let integrationOwnerSub = String(storedSettings.integrationOwnerSub||'');
let userPreferences = storedSettings.userPreferences&&typeof storedSettings.userPreferences==='object'?storedSettings.userPreferences:{};
function normalizeApplications(items){return (Array.isArray(items)?items:[]).slice(0,100).map((item,index)=>{try{const url=cleanUrl(item?.url);if(!url)return null;return {id:String(item?.id||`app-${index}`).slice(0,100),name:String(item?.name||'Application').trim().slice(0,80),url}}catch{return null}}).filter(Boolean)}
let applications = normalizeApplications(storedSettings.applications);
let dashboard = {weatherLocation:String(storedSettings.dashboard?.weatherLocation||'San Francisco, CA').slice(0,120),displayName:String(storedSettings.dashboard?.displayName||'Mike').slice(0,80),revision:Number(storedSettings.dashboard?.revision||0)};
let integrations = {homeAssistant:{...emptyIntegrations.homeAssistant,...(storedSettings.integrations?.homeAssistant||{})},plex:{...emptyIntegrations.plex,...(storedSettings.integrations?.plex||{})},vikunja:{...emptyIntegrations.vikunja,...(storedSettings.integrations?.vikunja||{})},chores:{...emptyIntegrations.chores,...(storedSettings.integrations?.chores||{})},calendar:{...emptyIntegrations.calendar,...(storedSettings.integrations?.calendar||{})},arrs:{}};
if(integrations.homeAssistant.calendarEntity&&!integrations.homeAssistant.calendarEntity.startsWith('calendar.'))integrations.homeAssistant.calendarEntity=`calendar.${integrations.homeAssistant.calendarEntity}`;
for(const name of Object.keys(emptyIntegrations.arrs))integrations.arrs[name]={...emptyIntegrations.arrs[name],...(storedSettings.integrations?.arrs?.[name]||{})};
const mime = {'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.webmanifest':'application/manifest+json','.svg':'image/svg+xml','.png':'image/png'};
const clientConfig = {user:{name:process.env.HAVEN_USER_NAME||'Mike'},auth:{}};

async function persistSettings(){storedSettings={...storedSettings,auth:runtimeAuth,integrations,applications,dashboard,userPreferences,integrationOwnerSub};await writeFile(settingsFile,JSON.stringify(storedSettings,null,2),'utf8')}
async function writeClientConfig(){clientConfig.auth={...runtimeAuth,enabled:runtimeAuth.enabled&&!authBypass,adapterUrl:'/vendor/keycloak.js'};await writeFile(join(publicDir,'config.js'),`export default ${JSON.stringify(clientConfig)};\n`,'utf8')}
await writeClientConfig();

function securityHeaders(){
  let keycloakOrigin='';
  try{keycloakOrigin=runtimeAuth.url?new URL(runtimeAuth.url).origin:''}catch{}
  return {'X-Content-Type-Options':'nosniff','X-Frame-Options':'SAMEORIGIN','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(), microphone=(), geolocation=()','Content-Security-Policy':`default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https: ${keycloakOrigin}; img-src 'self' data: blob: http: https:; frame-ancestors 'self'`};
}
function send(res,status,body,type='application/json'){res.writeHead(status,{...securityHeaders(),'Content-Type':type,'Cache-Control':'no-store'});res.end(type==='application/json'&&typeof body!=='string'?JSON.stringify(body):body)}
async function readJson(req){let body='';for await(const chunk of req){body+=chunk;if(body.length>65536)throw new Error('Request too large')}return JSON.parse(body||'{}')}
function setupAuthorized(req,res){if(!setupToken){send(res,503,{error:'HAVEN_SETUP_TOKEN is not configured in Portainer'});return false}if(req.headers['x-haven-setup-token']!==setupToken){send(res,403,{error:'Invalid setup token'});return false}return true}
function cleanUrl(value){const text=String(value||'').trim().replace(/\/$/,'');if(!text)return '';const parsed=new URL(text);if(!['http:','https:'].includes(parsed.protocol))throw new Error('Only http and https URLs are allowed');return text}

async function authenticatedIdentity(req){
  if(!runtimeAuth.enabled||!runtimeAuth.url||!runtimeAuth.realm)return false;
  const authorization=req.headers.authorization;
  if(!authorization?.startsWith('Bearer '))return false;
  try{const response=await fetch(`${runtimeAuth.url}/realms/${encodeURIComponent(runtimeAuth.realm)}/protocol/openid-connect/userinfo`,{headers:{Authorization:authorization},signal:AbortSignal.timeout(5000)});return response.ok?await response.json():false}catch{return false}
}
async function authenticated(req){return Boolean(await authenticatedIdentity(req))}
async function requireAuth(req,res){if(await authenticated(req))return true;send(res,401,{error:'Keycloak authentication required'});return false}
async function integrationOwnerAuthorized(req,res){const identity=await authenticatedIdentity(req);if(identity?.sub&&(!integrationOwnerSub||integrationOwnerSub===identity.sub)){if(!integrationOwnerSub){integrationOwnerSub=identity.sub;await persistSettings()}return true}return setupAuthorized(req,res)}

async function configureKeycloak(req,res){
  if(!setupAuthorized(req,res))return;
  try{const body=await readJson(req),url=cleanUrl(body.url),realm=String(body.realm||'').trim(),clientId=String(body.clientId||'').trim();if(body.enabled&&(!url||!realm||!clientId))return send(res,400,{error:'URL, realm, and client ID are required'});runtimeAuth={enabled:Boolean(body.enabled),url,realm,clientId:clientId||'haven'};await persistSettings();await writeClientConfig();return send(res,200,{ok:true})}catch(error){return send(res,400,{error:error.message||'Invalid settings'})}
}
async function applicationsApi(req,res){if(!await requireAuth(req,res))return;if(req.method==='GET')return send(res,200,{applications});if(req.method==='PUT'){try{const body=await readJson(req);applications=normalizeApplications(body.applications);await persistSettings();return send(res,200,{ok:true,applications})}catch(error){return send(res,400,{error:error.message||'Invalid applications'})}}return send(res,405,{error:'Method not allowed'})}
async function dashboardApi(req,res){if(!await requireAuth(req,res))return;if(req.method==='GET')return send(res,200,dashboard);if(req.method==='PUT'){try{const body=await readJson(req);dashboard={weatherLocation:String(body.weatherLocation||'San Francisco, CA').trim().slice(0,120),displayName:String(body.displayName||'Mike').trim().slice(0,80),revision:Date.now()};await persistSettings();return send(res,200,dashboard)}catch(error){return send(res,400,{error:error.message||'Invalid dashboard settings'})}}return send(res,405,{error:'Method not allowed'})}
const defaultWidgets=['weather','home-status','applications','plex','quick-actions','vikunja','chores'];
function normalizeWidgetPrefs(input){const order=[...new Set((Array.isArray(input?.order)?input.order:defaultWidgets).filter(id=>defaultWidgets.includes(id)))];for(const id of defaultWidgets)if(!order.includes(id))order.push(id);const hidden=(Array.isArray(input?.hidden)?input.hidden:[]).filter(id=>defaultWidgets.includes(id)),sizes={},wideDefaults=new Set(['applications','vikunja','chores']);for(const id of defaultWidgets)sizes[id]=['small','medium','wide'].includes(input?.sizes?.[id])?input.sizes[id]:wideDefaults.has(id)?'wide':'medium';return {order,hidden,sizes}}
async function meApi(req,res){const identity=await authenticatedIdentity(req);if(!identity)return send(res,401,{error:'Keycloak authentication required'});const current=userPreferences[identity.sub]||{},fullName=identity.name||identity.preferred_username||identity.email||'Haven user',profile={sub:identity.sub,name:identity.given_name||String(fullName).trim().split(/\s+/)[0],username:identity.preferred_username||'',email:identity.email||'',widgets:normalizeWidgetPrefs(current.widgets),vikunjaUserId:current.vikunjaUserId??null,vikunjaRejected:Boolean(current.vikunjaRejected)};if(req.method==='GET')return send(res,200,profile);if(req.method==='PUT'){const body=await readJson(req),next={...current};if(body.widgets)next.widgets=normalizeWidgetPrefs(body.widgets);if(Object.hasOwn(body,'vikunjaUserId')){next.vikunjaUserId=body.vikunjaUserId===null?null:Number(body.vikunjaUserId);next.vikunjaRejected=Boolean(body.vikunjaRejected)}userPreferences[identity.sub]=next;await persistSettings();return send(res,200,{...profile,...next,widgets:normalizeWidgetPrefs(next.widgets)})}return send(res,405,{error:'Method not allowed'})}
function mergeSecretService(input,previous,secretKey){const enteredUrl=String(input?.url||'').trim(),enteredSecret=String(input?.[secretKey]||'').trim();return {url:enteredUrl?cleanUrl(enteredUrl):previous?.url||'',[secretKey]:enteredSecret||previous?.[secretKey]||''}}
function normalizeQuickActions(actions){return (Array.isArray(actions)?actions:[]).slice(0,12).map((action,index)=>({id:String(action.id||`action-${index}`),name:String(action.name||'Action').trim().slice(0,60),entityId:String(action.entityId||'').trim(),service:['toggle','turn_on','turn_off','lock','unlock','open_cover','close_cover'].includes(action.service)?action.service:'toggle'})).filter(action=>/^[a-z_]+\.[a-zA-Z0-9_]+$/.test(action.entityId))}
async function configureIntegrations(req,res){
  if(!await requireAuth(req,res))return;
  try{
    const body=await readJson(req),haCredentials=mergeSecretService(body.homeAssistant,integrations.homeAssistant,'token'),enteredCalendarEntity=String(body.homeAssistant?.calendarEntity||'').trim(),rawCalendarEntity=enteredCalendarEntity||integrations.homeAssistant.calendarEntity,calendarEntity=rawCalendarEntity&&!rawCalendarEntity.startsWith('calendar.')?`calendar.${rawCalendarEntity}`:rawCalendarEntity,enteredChoreUrl=String(body.chores?.url||'').trim(),next={homeAssistant:{...haCredentials,calendarEntity,quickActions:normalizeQuickActions(body.homeAssistant?.quickActions??integrations.homeAssistant.quickActions)},plex:mergeSecretService(body.plex,integrations.plex,'token'),vikunja:mergeSecretService(body.vikunja,integrations.vikunja,'token'),chores:{url:enteredChoreUrl?cleanUrl(enteredChoreUrl):integrations.chores.url},calendar:{icsUrl:String(body.calendar?.icsUrl||'').trim()?cleanUrl(body.calendar.icsUrl):integrations.calendar.icsUrl},arrs:{}};
    for(const name of Object.keys(emptyIntegrations.arrs))next.arrs[name]=mergeSecretService(body.arrs?.[name],integrations.arrs[name],'apiKey');
    integrations=next;await persistSettings();return send(res,200,{ok:true});
  }catch(error){return send(res,400,{error:error.message||'Invalid integration settings'})}
}

const weatherDescriptions={0:'Clear sky',1:'Mainly clear',2:'Partly cloudy',3:'Overcast',45:'Foggy',48:'Rime fog',51:'Light drizzle',53:'Drizzle',55:'Heavy drizzle',61:'Light rain',63:'Rain',65:'Heavy rain',71:'Light snow',73:'Snow',75:'Heavy snow',80:'Rain showers',81:'Rain showers',82:'Heavy showers',95:'Thunderstorms',96:'Thunderstorms',99:'Severe thunderstorms'};
async function weather(res,url){
  const location=String(url.searchParams.get('location')||'').trim();if(!location)return send(res,400,{error:'Weather location is required'});
  try{
    const geoUrl=new URL('https://geocoding-api.open-meteo.com/v1/search');geoUrl.search=new URLSearchParams({name:location,count:'1',language:'en',format:'json'});
    const geo=await (await fetch(geoUrl,{signal:AbortSignal.timeout(8000)})).json(),place=geo.results?.[0];if(!place)return send(res,404,{error:'Location not found'});
    const forecastUrl=new URL('https://api.open-meteo.com/v1/forecast');forecastUrl.search=new URLSearchParams({latitude:String(place.latitude),longitude:String(place.longitude),current:'temperature_2m,relative_humidity_2m,weather_code,is_day',hourly:'temperature_2m,weather_code',temperature_unit:'fahrenheit',forecast_days:'2',timezone:'auto'});
    const data=await (await fetch(forecastUrl,{signal:AbortSignal.timeout(8000)})).json();
    const start=Math.max(0,data.hourly.time.findIndex(time=>time>=data.current.time));const hourly=data.hourly.time.slice(start,start+5).map((time,index)=>({time,temperature:Math.round(data.hourly.temperature_2m[start+index]),code:data.hourly.weather_code[start+index]}));
    return send(res,200,{location:[place.name,place.admin1].filter(Boolean).join(', '),temperature:Math.round(data.current.temperature_2m),humidity:Math.round(data.current.relative_humidity_2m),code:data.current.weather_code,condition:weatherDescriptions[data.current.weather_code]||'Current conditions',isDay:Boolean(data.current.is_day),hourly});
  }catch{return send(res,502,{error:'Weather service could not be reached'})}
}

function xmlDecode(value=''){return value.replaceAll('&amp;','&').replaceAll('&quot;','"').replaceAll('&apos;',"'").replaceAll('&lt;','<').replaceAll('&gt;','>')}
function xmlAttributes(text){const result={};for(const match of text.matchAll(/([\w:]+)="([^"]*)"/g))result[match[1]]=xmlDecode(match[2]);return result}
async function plexRecent(req,res){
  if(!await requireAuth(req,res))return;if(!integrations.plex.url||!integrations.plex.token)return send(res,503,{error:'Plex is not configured'});
  try{const response=await fetch(`${integrations.plex.url}/library/recentlyAdded?X-Plex-Token=${encodeURIComponent(integrations.plex.token)}`,{headers:{Accept:'application/xml'},signal:AbortSignal.timeout(10000)});if(!response.ok)return send(res,502,{error:`Plex returned ${response.status}`});const xml=await response.text(),items=[],seen=new Set();for(const match of xml.matchAll(/<Video\b([^>]*)>/g)){const item=xmlAttributes(match[1]),type=item.type||'';if(!['movie','episode'].includes(type)||!item.title)continue;const key=type==='episode'?(item.grandparentRatingKey||item.grandparentTitle):item.ratingKey;if(key&&seen.has(key))continue;if(key)seen.add(key);items.push({title:type==='episode'?(item.grandparentTitle||item.title):item.title,subtitle:type==='episode'?[item.parentTitle,item.title].filter(Boolean).join(' · '):'',year:item.year||'',type:type==='episode'?'TV':'Movie',addedAt:Number(item.addedAt||0),thumb:(type==='episode'?(item.grandparentThumb||item.thumb):item.thumb)?`/api/plex/image?path=${encodeURIComponent(type==='episode'?(item.grandparentThumb||item.thumb):item.thumb)}`:''});if(items.length===12)break}return send(res,200,{items})}catch{return send(res,502,{error:'Plex could not be reached'})}
}
async function plexImage(req,res,url){
  if(!await requireAuth(req,res))return;if(!integrations.plex.url||!integrations.plex.token)return send(res,503,{error:'Plex is not configured'});const path=String(url.searchParams.get('path')||'');if(!path.startsWith('/'))return send(res,400,{error:'Invalid image path'});
  try{const upstream=await fetch(`${integrations.plex.url}${path}${path.includes('?')?'&':'?'}X-Plex-Token=${encodeURIComponent(integrations.plex.token)}`,{signal:AbortSignal.timeout(10000)});const body=Buffer.from(await upstream.arrayBuffer());res.writeHead(upstream.status,{...securityHeaders(),'Content-Type':upstream.headers.get('content-type')||'image/jpeg','Cache-Control':'private, max-age=3600'});res.end(body)}catch{return send(res,502,{error:'Plex image unavailable'})}
}

function parseIcsDate(value){const text=String(value||'').replace(/^.*:/,'');const match=text.match(/^(\d{4})(\d{2})(\d{2})(?:T(\d{2})(\d{2})(\d{2}))?(Z)?$/);if(!match)return null;const parts=match.slice(1,7).map(Number);return match[7]?new Date(Date.UTC(parts[0],parts[1]-1,parts[2],parts[3]||0,parts[4]||0,parts[5]||0)):new Date(parts[0],parts[1]-1,parts[2],parts[3]||0,parts[4]||0,parts[5]||0)}
function parseCalendar(text){const unfolded=text.replace(/\r?\n[ \t]/g,''),now=Date.now()-86400000,events=[];for(const block of unfolded.split('BEGIN:VEVENT').slice(1)){const body=block.split('END:VEVENT')[0],lines=body.split(/\r?\n/),summary=lines.find(line=>line.startsWith('SUMMARY'))?.replace(/^SUMMARY[^:]*:/,'').replace(/\\,/g,',').replace(/\\n/g,' ')||'Untitled event',start=parseIcsDate(lines.find(line=>line.startsWith('DTSTART'))),end=parseIcsDate(lines.find(line=>line.startsWith('DTEND')))||start;if(start&&end?.getTime()>=now)events.push({summary,start:start.toISOString(),end:end.toISOString(),allDay:!lines.find(line=>line.startsWith('DTSTART'))?.includes('T')})}return events.sort((a,b)=>a.start.localeCompare(b.start)).slice(0,20)}
async function calendarEvents(req,res){if(!await requireAuth(req,res))return;if(!integrations.calendar.icsUrl)return send(res,503,{error:'Calendar is not configured'});try{const response=await fetch(integrations.calendar.icsUrl,{signal:AbortSignal.timeout(10000)});if(!response.ok)return send(res,502,{error:`Calendar returned ${response.status}`});return send(res,200,{events:parseCalendar(await response.text())})}catch{return send(res,502,{error:'Calendar could not be reached'})}}

async function testIntegration(req,res,url){
  if(!await requireAuth(req,res))return;const service=String(url.searchParams.get('service')||'');
  try{let target,headers={};if(service==='homeAssistant'){const config=integrations.homeAssistant;if(!config.url||!config.token)throw new Error('Home Assistant is not configured');target=`${config.url}/api/`;headers.Authorization=`Bearer ${config.token}`}else if(service==='plex'){if(!integrations.plex.url||!integrations.plex.token)throw new Error('Plex is not configured');target=`${integrations.plex.url}/identity`;headers['X-Plex-Token']=integrations.plex.token}else if(service==='vikunja'){if(!integrations.vikunja.url||!integrations.vikunja.token)throw new Error('Vikunja is not configured');target=`${integrations.vikunja.url}/api/v1/user`;headers.Authorization=`Bearer ${integrations.vikunja.token}`}else if(service==='homeAssistantCalendar'){const config=integrations.homeAssistant,entity=config.calendarEntity;if(!config.url||!config.token||!entity)throw new Error('Home Assistant calendar is not configured');const start=new Date(),end=new Date(start.getTime()+86400000),query=new URLSearchParams({start:start.toISOString(),end:end.toISOString()});target=`${config.url}/api/calendars/${encodeURIComponent(entity)}?${query}`;headers.Authorization=`Bearer ${config.token}`}else if(service==='chores'){if(!integrations.chores.url)throw new Error('Chore app is not configured');target=`${integrations.chores.url}/api/summary`}else if(service==='calendar'){if(!integrations.calendar.icsUrl)throw new Error('Calendar is not configured');target=integrations.calendar.icsUrl}else if(integrations.arrs[service]){const config=integrations.arrs[service];if(!config.url||!config.apiKey)throw new Error(`${service} is not configured`);target=`${config.url}/api/v3/system/status`;headers['X-Api-Key']=config.apiKey}else throw new Error('Unknown integration');const response=await fetch(target,{headers,signal:AbortSignal.timeout(8000)});return send(res,response.ok?200:502,{ok:response.ok,status:response.status})}catch(error){return send(res,502,{error:error.message||'Connection failed'})}
}

async function haFetch(path,options={}){const config=integrations.homeAssistant;if(!config.url||!config.token)throw new Error('Home Assistant is not configured');return fetch(`${config.url}${path}`,{...options,headers:{Authorization:`Bearer ${config.token}`,'Content-Type':'application/json',...(options.headers||{})},signal:AbortSignal.timeout(10000)})}
const entityView=state=>({entityId:state.entity_id,state:state.state,name:state.attributes?.friendly_name||state.entity_id.split('.')[1].replaceAll('_',' '),domain:state.entity_id.split('.')[0],unit:state.attributes?.unit_of_measurement||'',deviceClass:state.attributes?.device_class||''});
async function homeAssistantDashboard(req,res){if(!await requireAuth(req,res))return;try{const response=await haFetch('/api/states');if(!response.ok)return send(res,502,{error:`Home Assistant returned ${response.status}`});const states=await response.json(),entities=states.filter(item=>['light','switch','lock','cover','scene','script'].includes(item.entity_id.split('.')[0])).map(entityView),temperature=states.find(item=>item.attributes?.device_class==='temperature'&&Number.isFinite(Number(item.state))),humidity=states.find(item=>item.attributes?.device_class==='humidity'&&Number.isFinite(Number(item.state))),lights=states.filter(item=>item.entity_id.startsWith('light.')),locks=states.filter(item=>item.entity_id.startsWith('lock.'));return send(res,200,{summary:{temperature:temperature?`${Math.round(Number(temperature.state))}${temperature.attributes?.unit_of_measurement||'°'}`:'—',humidity:humidity?`${Math.round(Number(humidity.state))}${humidity.attributes?.unit_of_measurement||'%'}`:'—',lightsOn:lights.filter(item=>item.state==='on').length,lightsTotal:lights.length,locksLocked:locks.filter(item=>item.state==='locked').length,locksTotal:locks.length},entities,quickActions:integrations.homeAssistant.quickActions||[]})}catch(error){return send(res,502,{error:error.message||'Home Assistant could not be reached'})}}
async function homeAssistantAction(req,res){if(!await requireAuth(req,res))return;try{const body=await readJson(req),entityId=String(body.entityId||''),domain=entityId.split('.')[0];if(!/^[a-z_]+\.[a-zA-Z0-9_]+$/.test(entityId))return send(res,400,{error:'Invalid entity ID'});const allowed={light:['toggle','turn_on','turn_off'],switch:['toggle','turn_on','turn_off'],lock:['lock','unlock'],cover:['open_cover','close_cover'],scene:['turn_on'],script:['turn_on']},requested=String(body.service||'toggle'),service=domain==='scene'||domain==='script'?'turn_on':requested;if(!allowed[domain]?.includes(service))return send(res,400,{error:'That action is not allowed'});const upstream=await haFetch(`/api/services/${domain}/${service}`,{method:'POST',body:JSON.stringify({entity_id:entityId})});if(!upstream.ok)return send(res,502,{error:`Home Assistant returned ${upstream.status}`});return send(res,200,{ok:true})}catch(error){return send(res,502,{error:error.message||'Home Assistant action failed'})}}
async function homeAssistantCalendar(req,res){if(!await requireAuth(req,res))return;const entity=integrations.homeAssistant.calendarEntity;if(!entity)return send(res,503,{error:'Home Assistant calendar entity is not configured'});try{const requestUrl=new URL(req.url,'http://haven'),requestedStart=new Date(requestUrl.searchParams.get('start')||Date.now()),requestedEnd=new Date(requestUrl.searchParams.get('end')||requestedStart.getTime()+31*86400000),start=Number.isNaN(requestedStart.getTime())?new Date():requestedStart,maxEnd=new Date(start.getTime()+93*86400000),end=Number.isNaN(requestedEnd.getTime())||requestedEnd<=start||requestedEnd>maxEnd?maxEnd:requestedEnd,query=new URLSearchParams({start:start.toISOString(),end:end.toISOString()}),response=await haFetch(`/api/calendars/${encodeURIComponent(entity)}?${query}`);if(!response.ok)return send(res,502,{error:`Home Assistant returned ${response.status}`});const events=[];for(const event of await response.json()){const startValue=event.start?.dateTime||event.start?.date,endValue=event.end?.dateTime||event.end?.date,startDate=new Date(startValue),endDate=new Date(endValue||startValue);if(!startValue||Number.isNaN(startDate.getTime()))continue;events.push({summary:event.summary||'Untitled event',start:startDate.toISOString(),end:Number.isNaN(endDate.getTime())?startDate.toISOString():endDate.toISOString(),allDay:Boolean(event.start?.date&&!event.start?.dateTime),date:event.start?.date||'',endDate:event.end?.date||'',description:event.description||''})}return send(res,200,{events})}catch(error){return send(res,502,{error:error.message||'Home Assistant calendar could not be reached'})}}
async function vikunjaOpenTasks(){const config=integrations.vikunja;if(!config.url||!config.token)throw new Error('Vikunja is not configured');const headers={Authorization:`Bearer ${config.token}`},query=new URLSearchParams({filter:'done = false',filter_include_nulls:'false',sort_by:'due_date',order_by:'asc',per_page:'100'});let response=await fetch(`${config.url}/api/v1/tasks?${query}`,{headers,signal:AbortSignal.timeout(10000)});if(response.status===404)response=await fetch(`${config.url}/api/v1/tasks/all?${query}`,{headers,signal:AbortSignal.timeout(10000)});if(!response.ok)throw new Error(`Vikunja returned ${response.status}`);return response.json()}
function vikunjaPeople(tasks){const people=new Map();for(const task of tasks)for(const person of task.assignees||[])if(person?.id!=null)people.set(String(person.id),{id:Number(person.id),name:person.name||person.username||person.email||`User ${person.id}`,username:person.username||'',email:person.email||''});return [...people.values()]}
function suggestedVikunjaUser(identity,people){const terms=[identity.email,identity.preferred_username,identity.name].filter(Boolean).map(value=>String(value).toLowerCase());return people.find(person=>terms.some(term=>[person.email,person.username,person.name].some(value=>String(value||'').toLowerCase()===term)))||null}
async function vikunjaUsers(req,res){const identity=await authenticatedIdentity(req);if(!identity)return send(res,401,{error:'Keycloak authentication required'});try{const tasks=await vikunjaOpenTasks(),users=vikunjaPeople(tasks),prefs=userPreferences[identity.sub]||{};return send(res,200,{users,suggested:prefs.vikunjaRejected?null:suggestedVikunjaUser(identity,users),selectedUserId:prefs.vikunjaUserId??null})}catch(error){return send(res,502,{error:error.message||'Vikunja users could not be loaded'})}}
async function vikunjaTasks(req,res){const identity=await authenticatedIdentity(req);if(!identity)return send(res,401,{error:'Keycloak authentication required'});const config=integrations.vikunja;if(!config.url||!config.token)return send(res,503,{error:'Vikunja is not configured'});try{const allTasks=await vikunjaOpenTasks(),people=vikunjaPeople(allTasks),prefs=userPreferences[identity.sub]||{},suggested=prefs.vikunjaRejected?null:suggestedVikunjaUser(identity,people),userId=prefs.vikunjaUserId??suggested?.id??null,tasks=userId===null?[]:allTasks.filter(task=>(task.assignees||[]).some(assignee=>String(assignee.id)===String(userId))).slice(0,8).map(task=>({id:task.id,title:task.title||'Untitled task',dueDate:task.due_date||'',priority:Number(task.priority||0),projectId:task.project_id||0}));return send(res,200,{url:config.url,tasks,mapped:Boolean(prefs.vikunjaUserId),suggested:!prefs.vikunjaUserId?suggested:null})}catch(error){return send(res,502,{error:error.message||'Vikunja could not be reached'})}}
const pendingList=(payload,key)=>Array.isArray(payload)?payload:Array.isArray(payload?.[key])?payload[key]:Array.isArray(payload?.[`pending_${key}`])?payload[`pending_${key}`]:Array.isArray(payload?.pending)?payload.pending:Array.isArray(payload?.items)?payload.items:Array.isArray(payload?.data)?payload.data:[];
async function choreRequests(req,res){if(!await requireAuth(req,res))return;const config=integrations.chores;if(!config.url)return send(res,503,{error:'Chore app is not configured'});try{const [choresResponse,rewardsResponse]=await Promise.all([fetch(`${config.url}/api/chores/pending`,{signal:AbortSignal.timeout(8000)}),fetch(`${config.url}/api/rewards/pending`,{signal:AbortSignal.timeout(8000)})]);if(!choresResponse.ok||!rewardsResponse.ok)return send(res,502,{error:`Chore app returned ${!choresResponse.ok?choresResponse.status:rewardsResponse.status}`});const chores=pendingList(await choresResponse.json(),'chores').map(item=>({kind:'Chore',title:item.chore_name||item.name||item.title||item.chore?.name||'Pending chore',person:item.child_name||item.child?.name||item.user_name||'',detail:item.notes||item.description||''})),rewards=pendingList(await rewardsResponse.json(),'rewards').map(item=>({kind:'Reward',title:item.reward_name||item.name||item.title||item.reward?.name||'Reward request',person:item.child_name||item.child?.name||item.user_name||'',detail:item.notes||item.description||''}));return send(res,200,{url:config.url,items:[...chores,...rewards].slice(0,10)})}catch(error){return send(res,502,{error:error.message||'Chore app could not be reached'})}}
async function appIcon(req,res,url){if(!await requireAuth(req,res))return;try{const target=cleanUrl(url.searchParams.get('url')),base=new URL(target),page=await fetch(base,{headers:{Accept:'text/html'},redirect:'follow',signal:AbortSignal.timeout(6000)}),html=(page.headers.get('content-type')||'').includes('text/html')?await page.text():'';let iconHref='';for(const match of html.matchAll(/<link\b[^>]*>/gi)){const tag=match[0];if(!/rel=["'][^"']*icon/i.test(tag))continue;iconHref=tag.match(/href=["']([^"']+)/i)?.[1]||'';if(iconHref)break}const candidates=[iconHref?new URL(iconHref,page.url||base).href:'',new URL('/favicon.ico',page.url||base).href].filter(Boolean);for(const candidate of candidates){const icon=await fetch(candidate,{redirect:'follow',signal:AbortSignal.timeout(6000)});if(!icon.ok)continue;const type=icon.headers.get('content-type')||'';if(!type.startsWith('image/')&&!candidate.endsWith('.ico'))continue;const body=Buffer.from(await icon.arrayBuffer());if(body.length>2097152)continue;res.writeHead(200,{...securityHeaders(),'Content-Type':type||'image/x-icon','Cache-Control':'private, max-age=86400'});return res.end(body)}return send(res,404,{error:'No application icon found'})}catch{return send(res,404,{error:'Application icon unavailable'})}}

async function homeAssistant(req,res,url){if(!await requireAuth(req,res))return;const config=integrations.homeAssistant;if(!config.url||!config.token)return send(res,503,{error:'Home Assistant is not configured on the server'});const suffix=url.pathname.replace('/api/home-assistant','')||'/api/';if(!suffix.startsWith('/api/'))return send(res,400,{error:'Only Home Assistant API paths are allowed'});try{const upstream=await fetch(`${config.url}${suffix}${url.search}`,{method:req.method,headers:{Authorization:`Bearer ${config.token}`,'Content-Type':req.headers['content-type']||'application/json'},signal:AbortSignal.timeout(10000)});const body=Buffer.from(await upstream.arrayBuffer());res.writeHead(upstream.status,{...securityHeaders(),'Content-Type':upstream.headers.get('content-type')||'application/json','Cache-Control':'no-store'});res.end(body)}catch{return send(res,502,{error:'Home Assistant could not be reached'})}}

function integrationStatus(includePrivate=false){const arrs={};for(const [name,config] of Object.entries(integrations.arrs))arrs[name]={configured:Boolean(config.url&&config.apiKey),...(includePrivate?{url:config.url}:{})};return {version,homeAssistant:{configured:Boolean(integrations.homeAssistant.url&&integrations.homeAssistant.token),...(includePrivate?{url:integrations.homeAssistant.url,calendarEntity:integrations.homeAssistant.calendarEntity||'',quickActions:integrations.homeAssistant.quickActions||[]}:{})},keycloak:{configured:Boolean(runtimeAuth.enabled&&runtimeAuth.url&&runtimeAuth.realm),url:runtimeAuth.url,realm:runtimeAuth.realm,clientId:runtimeAuth.clientId,enabled:runtimeAuth.enabled,bypassed:authBypass},plex:{configured:Boolean(integrations.plex.url&&integrations.plex.token),...(includePrivate?{url:integrations.plex.url}:{})},vikunja:{configured:Boolean(integrations.vikunja.url&&integrations.vikunja.token),...(includePrivate?{url:integrations.vikunja.url}:{})},chores:{configured:Boolean(integrations.chores.url),...(includePrivate?{url:integrations.chores.url}:{})},calendar:{configured:Boolean(integrations.calendar.icsUrl)},arrs,setup:{available:Boolean(setupToken)}}}
async function staticFile(req,res,url){const requestPath=url.pathname==='/'?'/index.html':url.pathname,safePath=normalize(requestPath).replace(/^(\.\.[/\\])+/,'');let filePath=join(publicDir,safePath);if(!filePath.startsWith(publicDir))return send(res,403,'Forbidden','text/plain');try{if(!(await stat(filePath)).isFile())throw new Error()}catch{filePath=join(publicDir,'index.html')}try{const body=await readFile(filePath),cache=filePath.endsWith('config.js')?'no-store':filePath.endsWith('app.js')||filePath.endsWith('service-worker.js')?'no-cache':'public, max-age=3600';res.writeHead(200,{...securityHeaders(),'Content-Type':mime[extname(filePath)]||'application/octet-stream','Cache-Control':cache});res.end(body)}catch{return send(res,404,'Not found','text/plain')}}

createServer(async(req,res)=>{const url=new URL(req.url,'http://haven');if(url.pathname==='/health')return send(res,200,'healthy\n','text/plain');if(url.pathname==='/api/me')return meApi(req,res);if(url.pathname==='/api/applications')return applicationsApi(req,res);if(url.pathname==='/api/dashboard')return dashboardApi(req,res);if(url.pathname==='/api/integrations')return send(res,200,integrationStatus(await authenticated(req)));if(url.pathname==='/api/setup/keycloak'&&req.method==='POST')return configureKeycloak(req,res);if(url.pathname==='/api/setup/integrations'&&req.method==='POST')return configureIntegrations(req,res);if(url.pathname==='/api/weather')return weather(res,url);if(url.pathname==='/api/plex/recent')return plexRecent(req,res);if(url.pathname==='/api/plex/image')return plexImage(req,res,url);if(url.pathname==='/api/calendar/events')return calendarEvents(req,res);if(url.pathname==='/api/integrations/test')return testIntegration(req,res,url);if(url.pathname==='/api/home-assistant/dashboard')return homeAssistantDashboard(req,res);if(url.pathname==='/api/home-assistant/action'&&req.method==='POST')return homeAssistantAction(req,res);if(url.pathname==='/api/home-assistant/calendar')return homeAssistantCalendar(req,res);if(url.pathname==='/api/vikunja/users')return vikunjaUsers(req,res);if(url.pathname==='/api/vikunja/tasks')return vikunjaTasks(req,res);if(url.pathname==='/api/chores/pending')return choreRequests(req,res);if(url.pathname==='/api/app-icon')return appIcon(req,res,url);if(url.pathname.startsWith('/api/home-assistant'))return homeAssistant(req,res,url);return staticFile(req,res,url)}).listen(port,'0.0.0.0',()=>console.log(`Haven listening on ${port}`));
